
var e;e||(e=typeof Module !== 'undefined' ? Module : {});var k={},l;for(l in e)e.hasOwnProperty(l)&&(k[l]=e[l]);var aa=[],ba="./this.program";function q(a,b){throw b;}var ca="object"===typeof window,u="function"===typeof importScripts,v="",da,w,x,y,z;
if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)v=u?require("path").dirname(v)+"/":__dirname+"/",da=function(a,b){y||(y=require("fs"));z||(z=require("path"));a=z.normalize(a);return y.readFileSync(a,b?null:"utf8")},x=function(a){a=da(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||A("Assertion failed: undefined");return a},w=function(a,b,c){y||(y=require("fs"));z||(z=require("path"));a=z.normalize(a);y.readFile(a,function(d,f){d?c(d):b(f.buffer)})},
1<process.argv.length&&(ba=process.argv[1].replace(/\\/g,"/")),aa=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=e),process.on("uncaughtException",function(a){if(!(a instanceof B))throw a;}),process.on("unhandledRejection",function(a){throw a;}),q=function(a,b){if(noExitRuntime||0<ea)throw process.exitCode=a,b;b instanceof B||C("exiting due to exception: "+b);process.exit(a)},e.inspect=function(){return"[Emscripten Module object]"};else if(ca||u)u?v=self.location.href:"undefined"!==
typeof document&&document.currentScript&&(v=document.currentScript.src),v=0!==v.indexOf("blob:")?v.substr(0,v.replace(/[?#].*/,"").lastIndexOf("/")+1):"",da=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},u&&(x=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),w=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==
d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var fa=e.print||console.log.bind(console),C=e.printErr||console.warn.bind(console);for(l in k)k.hasOwnProperty(l)&&(e[l]=k[l]);k=null;e.arguments&&(aa=e.arguments);e.thisProgram&&(ba=e.thisProgram);e.quit&&(q=e.quit);var D;e.wasmBinary&&(D=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;"object"!==typeof WebAssembly&&A("no native wasm support detected");var ha,ia=!1;
function ja(a){var b=e["_"+a];b||A("Assertion failed: Cannot call unknown function "+(a+", make sure it is exported"));return b}function ka(a,b,c){var d={string:function(n){var p=0;if(null!==n&&void 0!==n&&0!==n){var r=(n.length<<2)+1;p=E(r);F(n,G,p,r)}return p},array:function(n){var p=E(n.length);la.set(n,p);return p}};a=ja(a);var f=[],h=0;if(c)for(var g=0;g<c.length;g++){var m=d[b[g]];m?(0===h&&(h=ma()),f[g]=m(c[g])):f[g]=c[g]}b=a.apply(null,f);b=function(n){0!==h&&na(h);return n}(b)}
var oa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function pa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&oa)return oa.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|h);else{var g=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|g:(f&7)<<18|h<<12|g<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function H(a,b){return a?pa(G,a,b):""}
function F(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var m=a.charCodeAt(++h);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-f}
function qa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function ra(a){var b=qa(a)+1,c=E(b);F(a,la,c,b);return c}var sa,la,G,ta,ua,I,va,J,K;
function wa(){var a=ha.buffer;sa=a;e.HEAP8=la=new Int8Array(a);e.HEAP16=ta=new Int16Array(a);e.HEAP32=I=new Int32Array(a);e.HEAPU8=G=new Uint8Array(a);e.HEAPU16=ua=new Uint16Array(a);e.HEAPU32=va=new Uint32Array(a);e.HEAPF32=J=new Float32Array(a);e.HEAPF64=K=new Float64Array(a)}var xa,ya=[],za=[],Aa=[],Ba=[],Ca=[],ea=0;function Da(){var a=e.preRun.shift();ya.unshift(a)}var L=0,Ea=null,M=null;e.preloadedImages={};e.preloadedAudios={};
function A(a){if(e.onAbort)e.onAbort(a);a="Aborted("+a+")";C(a);ia=!0;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function Fa(){return N.startsWith("data:application/octet-stream;base64,")}var N;N="lc80.wasm";if(!Fa()){var Ga=N;N=e.locateFile?e.locateFile(Ga,v):v+Ga}function Ha(){var a=N;try{if(a==N&&D)return new Uint8Array(D);if(x)return x(a);throw"both async and sync fetching of the wasm failed";}catch(b){A(b)}}
function Ia(){if(!D&&(ca||u)){if("function"===typeof fetch&&!N.startsWith("file://"))return fetch(N,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+N+"'";return a.arrayBuffer()}).catch(function(){return Ha()});if(w)return new Promise(function(a,b){w(N,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ha()})}
function Ja(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.Ec;"number"===typeof c?void 0===b.cc?O(c)():O(c)(b.cc):c(void 0===b.cc?null:b.cc)}}}var Ka=[];function O(a){var b=Ka[a];b||(a>=Ka.length&&(Ka.length=a+1),Ka[a]=b=xa.get(a));return b}var La=[null,[],[]],Ma={},Na=0;function Oa(){for(var a=P.length-1;0<=a;--a)Pa(a);P=[];Qa=[]}var Qa=[];function Ra(){if(Na&&Sa.Yb)for(var a=0;a<Qa.length;++a){var b=Qa[a];Qa.splice(a,1);--a;b.Nc.apply(null,b.Ac)}}var P=[];
function Pa(a){var b=P[a];b.target.removeEventListener(b.Rb,b.vc,b.Sb);P.splice(a,1)}function Q(a){function b(d){++Na;Sa=a;Ra();a.Ub(d);Ra();--Na}if(a.Tb)a.vc=b,a.target.addEventListener(a.Rb,b,a.Sb),P.push(a),Ta||(Ba.push(Oa),Ta=!0);else for(var c=0;c<P.length;++c)P[c].target==a.target&&P[c].Rb==a.Rb&&Pa(c--)}function Ua(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
var Ta,Sa,Va,Wa,Xa,Ya,Za,$a,ab,bb=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function R(a){a=2<a?H(a):a;return bb[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function cb(a){return 0>bb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function db(a,b,c,d,f,h){Va||(Va=S(256));a={target:R(a),Rb:h,Tb:d,Ub:function(g){g=g||event;var m=g.target.id?g.target.id:"",n=Va;F(Ua(g.target),G,n+0,128);F(m,G,n+128,128);O(d)(f,n,b)&&g.preventDefault()},Sb:c};Q(a)}
function eb(a,b,c,d,f,h){Wa||(Wa=S(176));a={target:R(a),Yb:!0,Rb:h,Tb:d,Ub:function(g){var m=Wa;K[m>>3]=g.timeStamp;var n=m>>2;I[n+2]=g.location;I[n+3]=g.ctrlKey;I[n+4]=g.shiftKey;I[n+5]=g.altKey;I[n+6]=g.metaKey;I[n+7]=g.repeat;I[n+8]=g.charCode;I[n+9]=g.keyCode;I[n+10]=g.which;F(g.key||"",G,m+44,32);F(g.code||"",G,m+76,32);F(g.char||"",G,m+108,32);F(g.locale||"",G,m+140,32);O(d)(f,m,b)&&g.preventDefault()},Sb:c};Q(a)}
function fb(a,b,c){K[a>>3]=b.timeStamp;a>>=2;I[a+2]=b.screenX;I[a+3]=b.screenY;I[a+4]=b.clientX;I[a+5]=b.clientY;I[a+6]=b.ctrlKey;I[a+7]=b.shiftKey;I[a+8]=b.altKey;I[a+9]=b.metaKey;ta[2*a+20]=b.button;ta[2*a+21]=b.buttons;I[a+11]=b.movementX;I[a+12]=b.movementY;c=cb(c);I[a+13]=b.clientX-c.left;I[a+14]=b.clientY-c.top}
function T(a,b,c,d,f,h){Xa||(Xa=S(72));a=R(a);Q({target:a,Yb:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Rb:h,Tb:d,Ub:function(g){g=g||event;fb(Xa,g,a);O(d)(f,Xa,b)&&g.preventDefault()},Sb:c})}function gb(a,b,c,d,f){Ya||(Ya=S(260));Q({target:a,Rb:f,Tb:d,Ub:function(h){h=h||event;var g=Ya,m=document.pointerLockElement||document.ec||document.hc||document.fc;I[g>>2]=!!m;var n=m&&m.id?m.id:"";F(Ua(m),G,g+4,128);F(n,G,g+132,128);O(d)(20,g,b)&&h.preventDefault()},Sb:c})}
function hb(a,b,c,d,f){Q({target:a,Rb:f,Tb:d,Ub:function(h){h=h||event;O(d)(38,0,b)&&h.preventDefault()},Sb:c})}
function ib(a,b,c,d){Za||(Za=S(36));a=R(a);Q({target:a,Rb:"resize",Tb:d,Ub:function(f){f=f||event;if(f.target==a){var h=document.body;if(h){var g=Za;I[g>>2]=f.detail;I[g+4>>2]=h.clientWidth;I[g+8>>2]=h.clientHeight;I[g+12>>2]=innerWidth;I[g+16>>2]=innerHeight;I[g+20>>2]=outerWidth;I[g+24>>2]=outerHeight;I[g+28>>2]=pageXOffset;I[g+32>>2]=pageYOffset;O(d)(10,g,b)&&f.preventDefault()}}},Sb:c})}
function jb(a,b,c,d,f,h){$a||($a=S(1696));a=R(a);Q({target:a,Yb:"touchstart"==h||"touchend"==h,Rb:h,Tb:d,Ub:function(g){for(var m,n={},p=g.touches,r=0;r<p.length;++r)m=p[r],m.kc=m.lc=0,n[m.identifier]=m;for(r=0;r<g.changedTouches.length;++r)m=g.changedTouches[r],m.kc=1,n[m.identifier]=m;for(r=0;r<g.targetTouches.length;++r)n[g.targetTouches[r].identifier].lc=1;p=$a;K[p>>3]=g.timeStamp;var t=p>>2;I[t+3]=g.ctrlKey;I[t+4]=g.shiftKey;I[t+5]=g.altKey;I[t+6]=g.metaKey;t+=7;var nb=cb(a),ob=0;for(r in n)if(m=
n[r],I[t]=m.identifier,I[t+1]=m.screenX,I[t+2]=m.screenY,I[t+3]=m.clientX,I[t+4]=m.clientY,I[t+5]=m.pageX,I[t+6]=m.pageY,I[t+7]=m.kc,I[t+8]=m.lc,I[t+9]=m.clientX-nb.left,I[t+10]=m.clientY-nb.top,t+=13,31<++ob)break;I[p+8>>2]=ob;O(d)(f,p,b)&&g.preventDefault()},Sb:c})}function kb(a,b,c,d,f,h){a={target:R(a),Rb:h,Tb:d,Ub:function(g){g=g||event;O(d)(f,0,b)&&g.preventDefault()},Sb:c};Q(a)}
function lb(a,b,c,d){ab||(ab=S(104));Q({target:a,Yb:!0,Rb:"wheel",Tb:d,Ub:function(f){f=f||event;var h=ab;fb(h,f,a);K[h+72>>3]=f.deltaX;K[h+80>>3]=f.deltaY;K[h+88>>3]=f.deltaZ;I[h+96>>2]=f.deltaMode;O(d)(9,h,b)&&f.preventDefault()},Sb:c})}
function mb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,h){b.drawArraysInstancedANGLE(c,d,f,h)},a.drawElementsInstanced=function(c,d,f,h,g){b.drawElementsInstancedANGLE(c,d,f,h,g)})}
function pb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function qb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function rb(a){a.Ic=a.getExtension("WEBGL_multi_draw")}
var sb=1,tb=[],U=[],ub=[],vb=[],wb=[],V=[],xb=[],yb={};function W(a){zb||(zb=a)}function Ab(a){for(var b=sb++,c=a.length;c<b;c++)a[c]=null;return b}function Bb(a,b){a.jc||(a.jc=a.getContext,a.getContext=function(d,f){f=a.jc(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl",b);return c?Cb(c,b):0}function Cb(a,b){var c=Ab(xb),d={Gc:c,attributes:b,version:b.yc,bc:a};a.canvas&&(a.canvas.zc=d);xb[c]=d;("undefined"===typeof b.ic||b.ic)&&Db(d);return c}
function Db(a){a||(a=Eb);if(!a.xc){a.xc=!0;var b=a.bc;mb(b);pb(b);qb(b);b.Cc=b.getExtension("EXT_disjoint_timer_query");rb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var zb,Eb,Fb=["default","low-power","high-performance"];function Gb(a,b,c,d){for(var f=0;f<a;f++){var h=X[c](),g=h&&Ab(d);h?(h.name=g,d[g]=h):W(1282);I[b+4*f>>2]=g}}
function Hb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=X.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=X.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":W(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:W(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)I[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(f){W(1280);C("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:W(1280);C("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}I[b>>2]=c}else W(1281)}function Ib(a){var b=qa(a)+1,c=S(b);F(a,G,c,b);return c}
function Jb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Kb(a,b,c,d,f){a-=5120;a=1==a?G:4==a?I:6==a?J:5==a||28922==a?va:ua;var h=31-Math.clz32(a.BYTES_PER_ELEMENT);return a.subarray(f>>h,f+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<h)+4-1&-4)>>h)}function Y(a){var b=X.uc;if(b){var c=b.Xb[a];"number"===typeof c&&(b.Xb[a]=c=X.getUniformLocation(b,b.sc[a]+(0<c?"["+c+"]":"")));return c}W(1282)}for(var Z=[],X,Lb=new Float32Array(288),Mb=0;288>Mb;++Mb)Z[Mb]=Lb.subarray(0,Mb+1);
var Sb={fa:function(){return 0},cb:function(){return 0},eb:function(){},ab:function(){A("")},M:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},Q:function(a,b,c){a=R(a);if(!a)return-4;a=cb(a);K[b>>3]=a.width;K[c>>3]=a.height;return 0},_a:function(a,b,c){G.copyWithin(a,b,b+c)},Ia:function(a,b){function c(d){O(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},$a:function(a){var b=G.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/
c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ha.grow(Math.min(2147483648,d)-sa.byteLength+65535>>>16);wa();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},R:function(a,b,c,d){db(a,b,c,d,12,"blur");return 0},K:function(a,b,c){a=R(a);if(!a)return-4;a.width=b;a.height=c;return 0},S:function(a,b,c,d){db(a,b,c,d,13,"focus");return 0},$:function(a,b,c,d){eb(a,b,c,d,2,"keydown");return 0},Z:function(a,b,c,d){eb(a,b,c,d,1,"keypress");return 0},_:function(a,
b,c,d){eb(a,b,c,d,3,"keyup");return 0},ha:function(a,b,c,d){T(a,b,c,d,5,"mousedown");return 0},ca:function(a,b,c,d){T(a,b,c,d,33,"mouseenter");return 0},ba:function(a,b,c,d){T(a,b,c,d,34,"mouseleave");return 0},da:function(a,b,c,d){T(a,b,c,d,8,"mousemove");return 0},ea:function(a,b,c,d){T(a,b,c,d,6,"mouseup");return 0},U:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.ec||document.body.hc||document.body.fc))return-1;a=R(a);if(!a)return-4;gb(a,b,c,
d,"pointerlockchange");gb(a,b,c,d,"mozpointerlockchange");gb(a,b,c,d,"webkitpointerlockchange");gb(a,b,c,d,"mspointerlockchange");return 0},T:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.ec||document.body.hc||document.body.fc))return-1;a=R(a);if(!a)return-4;hb(a,b,c,d,"pointerlockerror");hb(a,b,c,d,"mozpointerlockerror");hb(a,b,c,d,"webkitpointerlockerror");hb(a,b,c,d,"mspointerlockerror");return 0},Sa:function(a,b,c,d){ib(a,b,c,d);return 0},V:function(a,b,c,d){jb(a,
b,c,d,25,"touchcancel");return 0},W:function(a,b,c,d){jb(a,b,c,d,23,"touchend");return 0},X:function(a,b,c,d){jb(a,b,c,d,24,"touchmove");return 0},Y:function(a,b,c,d){jb(a,b,c,d,22,"touchstart");return 0},P:function(a,b,c,d){kb(a,b,c,d,31,"webglcontextlost");return 0},O:function(a,b,c,d){kb(a,b,c,d,32,"webglcontextrestored");return 0},aa:function(a,b,c,d){a=R(a);return"undefined"!==typeof a.onwheel?(lb(a,b,c,d),0):-1},A:function(a,b){b>>=2;b={alpha:!!I[b],depth:!!I[b+1],stencil:!!I[b+2],antialias:!!I[b+
3],premultipliedAlpha:!!I[b+4],preserveDrawingBuffer:!!I[b+5],powerPreference:Fb[I[b+6]],failIfMajorPerformanceCaveat:!!I[b+7],yc:I[b+8],Hc:I[b+9],ic:I[b+10],wc:I[b+11],Jc:I[b+12],Kc:I[b+13]};a=R(a);return!a||b.wc?0:Bb(a,b)},kb:function(a,b){a=xb[a];b=H(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&mb(X);"OES_vertex_array_object"==b&&pb(X);"WEBGL_draw_buffers"==b&&qb(X);"WEBGL_multi_draw"==b&&rb(X);return!!a.bc.getExtension(b)},za:function(a){a>>=2;for(var b=0;14>b;++b)I[a+
b]=0;I[a]=I[a+1]=I[a+3]=I[a+4]=I[a+8]=I[a+10]=1},tb:function(a){Eb=xb[a];e.Bc=X=Eb&&Eb.bc;return!a||X?0:-5},ga:function(){return 0},bb:function(a,b,c,d){a=Ma.Fc(a);b=Ma.Dc(a,b,c);I[d>>2]=b;return 0},Za:function(){},db:function(a,b,c,d){for(var f=0,h=0;h<c;h++){var g=I[b>>2],m=I[b+4>>2];b+=8;for(var n=0;n<m;n++){var p=G[g+n],r=La[a];0===p||10===p?((1===a?fa:C)(pa(r,0)),r.length=0):r.push(p)}f+=m}I[d>>2]=f;return 0},b:function(a){X.activeTexture(a)},D:function(a,b){X.attachShader(U[a],V[b])},c:function(a,
b){X.bindBuffer(a,tb[b])},y:function(a,b){X.bindFramebuffer(a,ub[b])},Ea:function(a,b){X.bindRenderbuffer(a,vb[b])},a:function(a,b){X.bindTexture(a,wb[b])},H:function(a,b,c,d){X.blendColor(a,b,c,d)},I:function(a,b){X.blendEquationSeparate(a,b)},J:function(a,b,c,d){X.blendFuncSeparate(a,b,c,d)},Ga:function(a,b,c,d){X.bufferData(a,c?G.subarray(c,c+b):b,d)},h:function(a,b,c,d){X.bufferSubData(a,b,G.subarray(d,d+c))},sb:function(a){X.clear(a)},qa:function(a,b,c,d){X.clearColor(a,b,c,d)},pa:function(a){X.clearDepth(a)},
oa:function(a){X.clearStencil(a)},o:function(a,b,c,d){X.colorMask(!!a,!!b,!!c,!!d)},ta:function(a){X.compileShader(V[a])},Ba:function(a,b,c,d,f,h,g,m){X.compressedTexImage2D(a,b,c,d,f,h,m?G.subarray(m,m+g):null)},ya:function(){var a=Ab(U),b=X.createProgram();b.name=a;b.ac=b.Zb=b.$b=0;b.dc=1;U[a]=b;return a},va:function(a){var b=Ab(V);V[b]=X.createShader(a);return b},E:function(a){X.cullFace(a)},Ma:function(a,b){for(var c=0;c<a;c++){var d=I[b+4*c>>2],f=tb[d];f&&(X.deleteBuffer(f),f.name=0,tb[d]=null)}},
i:function(a,b){for(var c=0;c<a;++c){var d=I[b+4*c>>2],f=ub[d];f&&(X.deleteFramebuffer(f),f.name=0,ub[d]=null)}},w:function(a){if(a){var b=U[a];b?(X.deleteProgram(b),b.name=0,U[a]=null):W(1281)}},N:function(a,b){for(var c=0;c<a;c++){var d=I[b+4*c>>2],f=vb[d];f&&(X.deleteRenderbuffer(f),f.name=0,vb[d]=null)}},s:function(a){if(a){var b=V[a];b?(X.deleteShader(b),V[a]=null):W(1281)}},La:function(a,b){for(var c=0;c<a;c++){var d=I[b+4*c>>2],f=wb[d];f&&(X.deleteTexture(f),f.name=0,wb[d]=null)}},v:function(a){X.depthFunc(a)},
u:function(a){X.depthMask(!!a)},d:function(a){X.disable(a)},L:function(a){X.disableVertexAttribArray(a)},ka:function(a,b,c){X.drawArrays(a,b,c)},la:function(a,b,c,d){X.drawElements(a,b,c,d)},f:function(a){X.enable(a)},pb:function(a){X.enableVertexAttribArray(a)},F:function(a){X.frontFace(a)},Ha:function(a,b){Gb(a,b,"createBuffer",tb)},Fa:function(a,b){Gb(a,b,"createRenderbuffer",vb)},Ca:function(a,b){Gb(a,b,"createTexture",wb)},ra:function(a,b){return X.getAttribLocation(U[a],H(b))},e:function(a,
b){Hb(a,b)},wa:function(a,b,c,d){a=X.getProgramInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?F(a,G,d,b):0;c&&(I[c>>2]=b)},C:function(a,b,c){if(c)if(a>=sb)W(1281);else if(a=U[a],35716==b)a=X.getProgramInfoLog(a),null===a&&(a="(unknown error)"),I[c>>2]=a.length+1;else if(35719==b){if(!a.ac)for(b=0;b<X.getProgramParameter(a,35718);++b)a.ac=Math.max(a.ac,X.getActiveUniform(a,b).name.length+1);I[c>>2]=a.ac}else if(35722==b){if(!a.Zb)for(b=0;b<X.getProgramParameter(a,35721);++b)a.Zb=Math.max(a.Zb,
X.getActiveAttrib(a,b).name.length+1);I[c>>2]=a.Zb}else if(35381==b){if(!a.$b)for(b=0;b<X.getProgramParameter(a,35382);++b)a.$b=Math.max(a.$b,X.getActiveUniformBlockName(a,b).length+1);I[c>>2]=a.$b}else I[c>>2]=X.getProgramParameter(a,b);else W(1281)},sa:function(a,b,c,d){a=X.getShaderInfoLog(V[a]);null===a&&(a="(unknown error)");b=0<b&&d?F(a,G,d,b):0;c&&(I[c>>2]=b)},z:function(a,b,c){c?35716==b?(a=X.getShaderInfoLog(V[a]),null===a&&(a="(unknown error)"),I[c>>2]=a?a.length+1:0):35720==b?(a=X.getShaderSource(V[a]),
I[c>>2]=a?a.length+1:0):I[c>>2]=X.getShaderParameter(V[a],b):W(1281)},Na:function(a){var b=yb[a];if(!b){switch(a){case 7939:b=X.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Ib(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=X.getParameter(a))||W(1280);b=b&&Ib(b);break;case 7938:b=Ib("OpenGL ES 2.0 ("+X.getParameter(7938)+")");break;case 35724:b=X.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&
(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Ib(b);break;default:W(1280)}yb[a]=b}return b},n:function(a,b){b=H(b);if(a=U[a]){var c=a,d=c.Xb,f=c.tc,h;if(!d)for(c.Xb=d={},c.sc={},h=0;h<X.getProgramParameter(c,35718);++h){var g=X.getActiveUniform(c,h);var m=g.name;g=g.size;var n=Jb(m);n=0<n?m.slice(0,n):m;var p=c.dc;c.dc+=g;f[n]=[g,p];for(m=0;m<g;++m)d[p]=m,c.sc[p++]=n}c=a.Xb;d=0;f=b;h=Jb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,f=b.slice(0,h));if((f=a.tc[f])&&d<f[0]&&(d+=f[1],c[d]=c[d]||X.getUniformLocation(a,
b)))return d}else W(1281);return-1},xa:function(a){a=U[a];X.linkProgram(a);a.Xb=0;a.tc={}},G:function(a,b){X.polygonOffset(a,b)},Da:function(a,b,c,d){X.renderbufferStorage(a,b,c,d)},l:function(a,b,c,d){X.scissor(a,b,c,d)},ua:function(a,b,c,d){for(var f="",h=0;h<b;++h){var g=d?I[d+4*h>>2]:-1;f+=H(I[c+4*h>>2],0>g?void 0:g)}X.shaderSource(V[a],f)},Ka:function(a,b,c){X.stencilFunc(a,b,c)},na:function(a,b,c,d){X.stencilFuncSeparate(a,b,c,d)},t:function(a){X.stencilMask(a)},Ja:function(a,b,c){X.stencilOp(a,
b,c)},ma:function(a,b,c,d){X.stencilOpSeparate(a,b,c,d)},Aa:function(a,b,c,d,f,h,g,m,n){X.texImage2D(a,b,c,d,f,h,g,m,n?Kb(m,g,d,f,n):null)},g:function(a,b,c){X.texParameteri(a,b,c)},ib:function(a,b,c,d,f,h,g,m,n){var p=null;n&&(p=Kb(m,g,f,h,n));X.texSubImage2D(a,b,c,d,f,h,g,m,p)},ob:function(a,b,c){if(288>=b)for(var d=Z[b-1],f=0;f<b;++f)d[f]=J[c+4*f>>2];else d=J.subarray(c>>2,c+4*b>>2);X.uniform1fv(Y(a),d)},B:function(a,b){X.uniform1i(Y(a),b)},nb:function(a,b,c){if(144>=b)for(var d=Z[2*b-1],f=0;f<
2*b;f+=2)d[f]=J[c+4*f>>2],d[f+1]=J[c+(4*f+4)>>2];else d=J.subarray(c>>2,c+8*b>>2);X.uniform2fv(Y(a),d)},mb:function(a,b,c){if(96>=b)for(var d=Z[3*b-1],f=0;f<3*b;f+=3)d[f]=J[c+4*f>>2],d[f+1]=J[c+(4*f+4)>>2],d[f+2]=J[c+(4*f+8)>>2];else d=J.subarray(c>>2,c+12*b>>2);X.uniform3fv(Y(a),d)},lb:function(a,b,c){if(72>=b){var d=Z[4*b-1],f=J;c>>=2;for(var h=0;h<4*b;h+=4){var g=c+h;d[h]=f[g];d[h+1]=f[g+1];d[h+2]=f[g+2];d[h+3]=f[g+3]}}else d=J.subarray(c>>2,c+16*b>>2);X.uniform4fv(Y(a),d)},jb:function(a,b,c,d){if(18>=
b){var f=Z[16*b-1],h=J;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;f[g]=h[m];f[g+1]=h[m+1];f[g+2]=h[m+2];f[g+3]=h[m+3];f[g+4]=h[m+4];f[g+5]=h[m+5];f[g+6]=h[m+6];f[g+7]=h[m+7];f[g+8]=h[m+8];f[g+9]=h[m+9];f[g+10]=h[m+10];f[g+11]=h[m+11];f[g+12]=h[m+12];f[g+13]=h[m+13];f[g+14]=h[m+14];f[g+15]=h[m+15]}}else f=J.subarray(d>>2,d+64*b>>2);X.uniformMatrix4fv(Y(a),!!c,f)},k:function(a){a=U[a];X.useProgram(a);X.uc=a},qb:function(a,b){X.vertexAttribDivisor(a,b)},rb:function(a,b,c,d,f,h){X.vertexAttribPointer(a,
b,c,!!d,f,h)},m:function(a,b,c,d){X.viewport(a,b,c,d)},Xa:function(){e.mc=function(a){0!=Nb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.mc)},Wa:function(){e.rc=function(a){a=a.clipboardData.getData("text");ka("_sapp_emsc_onpaste",["string"],[a])};window.addEventListener("paste",e.rc)},Va:function(a){e.Lc=[];a=H(a);a=document.getElementById(a);e.nc=function(b){b.stopPropagation();b.preventDefault()};e.oc=function(b){b.stopPropagation();b.preventDefault()};e.pc=
function(b){b.stopPropagation();b.preventDefault()};e.qc=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;e.Mc=c;Ob(c.length);var d;for(d=0;d<c.length;d++)ka("_sapp_emsc_drop",["number","string"],[d,c[d].name]);Pb(b.clientX,b.clientY)};a.addEventListener("dragenter",e.nc,!1);a.addEventListener("dragleave",e.oc,!1);a.addEventListener("dragover",e.pc,!1);a.addEventListener("drop",e.qc,!1)},Pa:function(){var a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},
r:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Qb()});document.body.append(a)},q:function(){document.getElementById("_sokol_app_input_element").focus()},Ya:function(a){a=H(a);e.Wb=document.getElementById(a);e.Wb||console.log("sokol_app.h: invalid target:"+a);e.Wb.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Ua:function(){window.removeEventListener("beforeunload",
e.mc)},Ta:function(){window.removeEventListener("paste",e.rc)},Ra:function(a){a=H(a);a=document.getElementById(a);a.removeEventListener("dragenter",e.nc);a.removeEventListener("dragleave",e.oc);a.removeEventListener("dragover",e.pc);a.removeEventListener("drop",e.qc)},x:function(){e.Wb&&e.Wb.requestPointerLock&&e.Wb.requestPointerLock()},Oa:function(a,b,c){var d=document.createElement("canvas");d.width=a;d.height=b;var f=d.getContext("2d"),h=f.createImageData(a,b);h.data.set(G.subarray(c,c+a*b*4));
f.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},p:function(){document.getElementById("_sokol_app_input_element").blur()},Qa:function(a){a=H(a);var b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=
1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},ub:function(){for(var a=(new URLSearchParams(window.location.search)).entries(),b=a.next();!b.done;b=a.next())ka("_sargs_add_kvp",["string","string"],[b.value[0],b.value[1]])},fb:function(){return e.Vb?e.Vb.bufferSize:0},hb:function(a,b,c){e.Qb=null;e.Vb=null;"undefined"!==typeof AudioContext?e.Qb=new AudioContext({sampleRate:a,latencyHint:"interactive"}):"undefined"!==typeof webkitAudioContext?
e.Qb=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}):(e.Qb=null,console.log("sokol_audio.h: no WebAudio support"));return e.Qb?(console.log("sokol_audio.h: sample rate ",e.Qb.sampleRate),e.Vb=e.Qb.createScriptProcessor(c,0,b),e.Vb.onaudioprocess=function(d){var f=d.outputBuffer.length,h=Rb(f);if(h)for(var g=d.outputBuffer.numberOfChannels,m=0;m<g;m++)for(var n=d.outputBuffer.getChannelData(m),p=0;p<f;p++)n[p]=J[(h>>2)+(g*p+m)]},e.Vb.connect(e.Qb.destination),a=function(){e.Qb&&"suspended"===
e.Qb.state&&e.Qb.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},gb:function(){return e.Qb?e.Qb.sampleRate:0},ja:function(){null!==e.Qb&&(e.Vb&&e.Vb.disconnect(),e.Qb.close(),e.Qb=null,e.Vb=null)},ia:function(){return navigator.userAgent.includes("Macintosh")?1:0},j:function(){return performance.now()}};
(function(){function a(f){e.asm=f.exports;ha=e.asm.vb;wa();xa=e.asm.Pb;za.unshift(e.asm.wb);L--;e.monitorRunDependencies&&e.monitorRunDependencies(L);0==L&&(null!==Ea&&(clearInterval(Ea),Ea=null),M&&(f=M,M=null,f()))}function b(f){a(f.instance)}function c(f){return Ia().then(function(h){return WebAssembly.instantiate(h,d)}).then(function(h){return h}).then(f,function(h){C("failed to asynchronously prepare wasm: "+h);A(h)})}var d={a:Sb};L++;e.monitorRunDependencies&&e.monitorRunDependencies(L);if(e.instantiateWasm)try{return e.instantiateWasm(d,
a)}catch(f){return C("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return D||"function"!==typeof WebAssembly.instantiateStreaming||Fa()||N.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(N,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(h){C("wasm streaming compile failed: "+h);C("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.wb).apply(null,arguments)};var Qb=e.__sapp_emsc_notify_keyboard_hidden=function(){return(Qb=e.__sapp_emsc_notify_keyboard_hidden=e.asm.xb).apply(null,arguments)};e.__sapp_emsc_onpaste=function(){return(e.__sapp_emsc_onpaste=e.asm.yb).apply(null,arguments)};
var Nb=e.__sapp_html5_get_ask_leave_site=function(){return(Nb=e.__sapp_html5_get_ask_leave_site=e.asm.zb).apply(null,arguments)},Ob=e.__sapp_emsc_begin_drop=function(){return(Ob=e.__sapp_emsc_begin_drop=e.asm.Ab).apply(null,arguments)};e.__sapp_emsc_drop=function(){return(e.__sapp_emsc_drop=e.asm.Bb).apply(null,arguments)};var Pb=e.__sapp_emsc_end_drop=function(){return(Pb=e.__sapp_emsc_end_drop=e.asm.Cb).apply(null,arguments)};
e.__sapp_emsc_invoke_fetch_cb=function(){return(e.__sapp_emsc_invoke_fetch_cb=e.asm.Db).apply(null,arguments)};e._main=function(){return(e._main=e.asm.Eb).apply(null,arguments)};var Rb=e.__saudio_emsc_pull=function(){return(Rb=e.__saudio_emsc_pull=e.asm.Fb).apply(null,arguments)};e.__sargs_add_kvp=function(){return(e.__sargs_add_kvp=e.asm.Gb).apply(null,arguments)};e.__sfetch_emsc_head_response=function(){return(e.__sfetch_emsc_head_response=e.asm.Hb).apply(null,arguments)};
e.__sfetch_emsc_get_response=function(){return(e.__sfetch_emsc_get_response=e.asm.Ib).apply(null,arguments)};e.__sfetch_emsc_failed_http_status=function(){return(e.__sfetch_emsc_failed_http_status=e.asm.Jb).apply(null,arguments)};e.__sfetch_emsc_failed_buffer_too_small=function(){return(e.__sfetch_emsc_failed_buffer_too_small=e.asm.Kb).apply(null,arguments)};
var S=e._malloc=function(){return(S=e._malloc=e.asm.Lb).apply(null,arguments)},ma=e.stackSave=function(){return(ma=e.stackSave=e.asm.Mb).apply(null,arguments)},na=e.stackRestore=function(){return(na=e.stackRestore=e.asm.Nb).apply(null,arguments)},E=e.stackAlloc=function(){return(E=e.stackAlloc=e.asm.Ob).apply(null,arguments)},Tb;function B(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}M=function Ub(){Tb||Vb();Tb||(M=Ub)};
function Vb(a){function b(){if(!Tb&&(Tb=!0,e.calledRun=!0,!ia)){Ja(za);Ja(Aa);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(Wb){var c=a,d=e._main;c=c||[];var f=c.length+1,h=E(4*(f+1));I[h>>2]=ra(ba);for(var g=1;g<f;g++)I[(h>>2)+g]=ra(c[g-1]);I[(h>>2)+f]=0;try{var m=d(f,h);if(!(noExitRuntime||0<ea)){if(e.onExit)e.onExit(m);ia=!0}q(m,new B(m))}catch(n){n instanceof B||"unwind"==n||q(1,n)}finally{}}if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)c=e.postRun.shift(),
Ca.unshift(c);Ja(Ca)}}a=a||aa;if(!(0<L)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Da();Ja(ya);0<L||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);b()},1)):b())}}e.run=Vb;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Wb=!0;e.noInitialRun&&(Wb=!1);Vb();
