
var e;e||(e=typeof Module !== 'undefined' ? Module : {});var k={},l;for(l in e)e.hasOwnProperty(l)&&(k[l]=e[l]);var aa=[],ba="./this.program";function q(a,b){throw b;}var ca="object"===typeof window,u="function"===typeof importScripts,v="",da,w,ea,x,y;
if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)v=u?require("path").dirname(v)+"/":__dirname+"/",da=function(a,b){x||(x=require("fs"));y||(y=require("path"));a=y.normalize(a);return x.readFileSync(a,b?null:"utf8")},ea=function(a){a=da(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||z("Assertion failed: undefined");return a},w=function(a,b,c){x||(x=require("fs"));y||(y=require("path"));a=y.normalize(a);x.readFile(a,function(d,f){d?c(d):b(f.buffer)})},
1<process.argv.length&&(ba=process.argv[1].replace(/\\/g,"/")),aa=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=e),process.on("uncaughtException",function(a){if(!(a instanceof fa))throw a;}),process.on("unhandledRejection",function(a){throw a;}),q=function(a,b){if(noExitRuntime||0<ha)throw process.exitCode=a,b;b instanceof fa||A("exiting due to exception: "+b);process.exit(a)},e.inspect=function(){return"[Emscripten Module object]"};else if(ca||u)u?v=self.location.href:"undefined"!==
typeof document&&document.currentScript&&(v=document.currentScript.src),v=0!==v.indexOf("blob:")?v.substr(0,v.replace(/[?#].*/,"").lastIndexOf("/")+1):"",da=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},u&&(ea=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),w=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==
d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ia=e.print||console.log.bind(console),A=e.printErr||console.warn.bind(console);for(l in k)k.hasOwnProperty(l)&&(e[l]=k[l]);k=null;e.arguments&&(aa=e.arguments);e.thisProgram&&(ba=e.thisProgram);e.quit&&(q=e.quit);var B;e.wasmBinary&&(B=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;"object"!==typeof WebAssembly&&z("no native wasm support detected");var ja,ka=!1;
function la(a){var b=e["_"+a];b||z("Assertion failed: Cannot call unknown function "+(a+", make sure it is exported"));return b}function ma(a,b,c){var d={string:function(n){var p=0;if(null!==n&&void 0!==n&&0!==n){var r=(n.length<<2)+1;p=C(r);D(n,E,p,r)}return p},array:function(n){var p=C(n.length);na.set(n,p);return p}};a=la(a);var f=[],h=0;if(c)for(var g=0;g<c.length;g++){var m=d[b[g]];m?(0===h&&(h=oa()),f[g]=m(c[g])):f[g]=c[g]}b=a.apply(null,f);b=function(n){0!==h&&pa(h);return n}(b)}
var qa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ra(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&qa)return qa.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|h);else{var g=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|g:(f&7)<<18|h<<12|g<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function F(a,b){return a?ra(E,a,b):""}
function D(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var m=a.charCodeAt(++h);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-f}
function sa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function ta(a){var b=sa(a)+1,c=C(b);D(a,na,c,b);return c}var ua,na,E,va,wa,G,xa,H,I;
function ya(){var a=ja.buffer;ua=a;e.HEAP8=na=new Int8Array(a);e.HEAP16=va=new Int16Array(a);e.HEAP32=G=new Int32Array(a);e.HEAPU8=E=new Uint8Array(a);e.HEAPU16=wa=new Uint16Array(a);e.HEAPU32=xa=new Uint32Array(a);e.HEAPF32=H=new Float32Array(a);e.HEAPF64=I=new Float64Array(a)}var za,Aa=[],Ba=[],Ca=[],Da=[],Ea=[],ha=0;function Fa(){var a=e.preRun.shift();Aa.unshift(a)}var J=0,Ga=null,K=null;e.preloadedImages={};e.preloadedAudios={};
function z(a){if(e.onAbort)e.onAbort(a);a="Aborted("+a+")";A(a);ka=!0;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function Ha(){return L.startsWith("data:application/octet-stream;base64,")}var L;L="pacman-ui.wasm";if(!Ha()){var Ia=L;L=e.locateFile?e.locateFile(Ia,v):v+Ia}function Ja(){var a=L;try{if(a==L&&B)return new Uint8Array(B);if(ea)return ea(a);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
function Ka(){if(!B&&(ca||u)){if("function"===typeof fetch&&!L.startsWith("file://"))return fetch(L,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+L+"'";return a.arrayBuffer()}).catch(function(){return Ja()});if(w)return new Promise(function(a,b){w(L,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ja()})}
function La(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.Hc;"number"===typeof c?void 0===b.fc?M(c)():M(c)(b.fc):c(void 0===b.fc?null:b.fc)}}}var Ma=[];function M(a){var b=Ma[a];b||(a>=Ma.length&&(Ma.length=a+1),Ma[a]=b=za.get(a));return b}var Na=[null,[],[]],Oa={},Pa=0;function Qa(){for(var a=N.length-1;0<=a;--a)Ra(a);N=[];Sa=[]}var Sa=[];function Ta(){if(Pa&&Ua.ac)for(var a=0;a<Sa.length;++a){var b=Sa[a];Sa.splice(a,1);--a;b.Qc.apply(null,b.Dc)}}var N=[];
function Ra(a){var b=N[a];b.target.removeEventListener(b.Ub,b.yc,b.Vb);N.splice(a,1)}function O(a){function b(d){++Pa;Ua=a;Ta();a.Xb(d);Ta();--Pa}if(a.Wb)a.yc=b,a.target.addEventListener(a.Ub,b,a.Vb),N.push(a),Va||(Da.push(Qa),Va=!0);else for(var c=0;c<N.length;++c)N[c].target==a.target&&N[c].Ub==a.Ub&&Ra(c--)}function Wa(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
var Va,Ua,Xa,Ya,Za,$a,ab,bb,cb,db=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function P(a){a=2<a?F(a):a;return db[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function eb(a){return 0>db.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function fb(a,b,c,d,f,h){Xa||(Xa=Q(256));a={target:P(a),Ub:h,Wb:d,Xb:function(g){g=g||event;var m=g.target.id?g.target.id:"",n=Xa;D(Wa(g.target),E,n+0,128);D(m,E,n+128,128);M(d)(f,n,b)&&g.preventDefault()},Vb:c};O(a)}
function gb(a,b,c,d,f,h){Ya||(Ya=Q(176));a={target:P(a),ac:!0,Ub:h,Wb:d,Xb:function(g){var m=Ya;I[m>>3]=g.timeStamp;var n=m>>2;G[n+2]=g.location;G[n+3]=g.ctrlKey;G[n+4]=g.shiftKey;G[n+5]=g.altKey;G[n+6]=g.metaKey;G[n+7]=g.repeat;G[n+8]=g.charCode;G[n+9]=g.keyCode;G[n+10]=g.which;D(g.key||"",E,m+44,32);D(g.code||"",E,m+76,32);D(g.char||"",E,m+108,32);D(g.locale||"",E,m+140,32);M(d)(f,m,b)&&g.preventDefault()},Vb:c};O(a)}
function hb(a,b,c){I[a>>3]=b.timeStamp;a>>=2;G[a+2]=b.screenX;G[a+3]=b.screenY;G[a+4]=b.clientX;G[a+5]=b.clientY;G[a+6]=b.ctrlKey;G[a+7]=b.shiftKey;G[a+8]=b.altKey;G[a+9]=b.metaKey;va[2*a+20]=b.button;va[2*a+21]=b.buttons;G[a+11]=b.movementX;G[a+12]=b.movementY;c=eb(c);G[a+13]=b.clientX-c.left;G[a+14]=b.clientY-c.top}
function R(a,b,c,d,f,h){Za||(Za=Q(72));a=P(a);O({target:a,ac:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Ub:h,Wb:d,Xb:function(g){g=g||event;hb(Za,g,a);M(d)(f,Za,b)&&g.preventDefault()},Vb:c})}function ib(a,b,c,d,f){$a||($a=Q(260));O({target:a,Ub:f,Wb:d,Xb:function(h){h=h||event;var g=$a,m=document.pointerLockElement||document.ic||document.kc||document.jc;G[g>>2]=!!m;var n=m&&m.id?m.id:"";D(Wa(m),E,g+4,128);D(n,E,g+132,128);M(d)(20,g,b)&&h.preventDefault()},Vb:c})}
function jb(a,b,c,d,f){O({target:a,Ub:f,Wb:d,Xb:function(h){h=h||event;M(d)(38,0,b)&&h.preventDefault()},Vb:c})}
function kb(a,b,c,d){ab||(ab=Q(36));a=P(a);O({target:a,Ub:"resize",Wb:d,Xb:function(f){f=f||event;if(f.target==a){var h=document.body;if(h){var g=ab;G[g>>2]=f.detail;G[g+4>>2]=h.clientWidth;G[g+8>>2]=h.clientHeight;G[g+12>>2]=innerWidth;G[g+16>>2]=innerHeight;G[g+20>>2]=outerWidth;G[g+24>>2]=outerHeight;G[g+28>>2]=pageXOffset;G[g+32>>2]=pageYOffset;M(d)(10,g,b)&&f.preventDefault()}}},Vb:c})}
function lb(a,b,c,d,f,h){bb||(bb=Q(1696));a=P(a);O({target:a,ac:"touchstart"==h||"touchend"==h,Ub:h,Wb:d,Xb:function(g){for(var m,n={},p=g.touches,r=0;r<p.length;++r)m=p[r],m.nc=m.oc=0,n[m.identifier]=m;for(r=0;r<g.changedTouches.length;++r)m=g.changedTouches[r],m.nc=1,n[m.identifier]=m;for(r=0;r<g.targetTouches.length;++r)n[g.targetTouches[r].identifier].oc=1;p=bb;I[p>>3]=g.timeStamp;var t=p>>2;G[t+3]=g.ctrlKey;G[t+4]=g.shiftKey;G[t+5]=g.altKey;G[t+6]=g.metaKey;t+=7;var nb=eb(a),ob=0;for(r in n)if(m=
n[r],G[t]=m.identifier,G[t+1]=m.screenX,G[t+2]=m.screenY,G[t+3]=m.clientX,G[t+4]=m.clientY,G[t+5]=m.pageX,G[t+6]=m.pageY,G[t+7]=m.nc,G[t+8]=m.oc,G[t+9]=m.clientX-nb.left,G[t+10]=m.clientY-nb.top,t+=13,31<++ob)break;G[p+8>>2]=ob;M(d)(f,p,b)&&g.preventDefault()},Vb:c})}function mb(a,b,c,d,f,h){a={target:P(a),Ub:h,Wb:d,Xb:function(g){g=g||event;M(d)(f,0,b)&&g.preventDefault()},Vb:c};O(a)}
function pb(a,b,c,d){cb||(cb=Q(104));O({target:a,ac:!0,Ub:"wheel",Wb:d,Xb:function(f){f=f||event;var h=cb;hb(h,f,a);I[h+72>>3]=f.deltaX;I[h+80>>3]=f.deltaY;I[h+88>>3]=f.deltaZ;G[h+96>>2]=f.deltaMode;M(d)(9,h,b)&&f.preventDefault()},Vb:c})}
function qb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,h){b.drawArraysInstancedANGLE(c,d,f,h)},a.drawElementsInstanced=function(c,d,f,h,g){b.drawElementsInstancedANGLE(c,d,f,h,g)})}
function rb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function sb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function tb(a){a.Lc=a.getExtension("WEBGL_multi_draw")}
var ub=1,vb=[],S=[],wb=[],T=[],U=[],V=[],xb=[],yb={};function W(a){zb||(zb=a)}function Ab(a){for(var b=ub++,c=a.length;c<b;c++)a[c]=null;return b}function Bb(a,b){a.mc||(a.mc=a.getContext,a.getContext=function(d,f){f=a.mc(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl",b);return c?Cb(c,b):0}function Cb(a,b){var c=Ab(xb),d={Jc:c,attributes:b,version:b.Bc,ec:a};a.canvas&&(a.canvas.Cc=d);xb[c]=d;("undefined"===typeof b.lc||b.lc)&&Db(d);return c}
function Db(a){a||(a=Eb);if(!a.Ac){a.Ac=!0;var b=a.ec;qb(b);rb(b);sb(b);b.Fc=b.getExtension("EXT_disjoint_timer_query");tb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var zb,Eb,Fb=["default","low-power","high-performance"];function Gb(a,b,c,d){for(var f=0;f<a;f++){var h=X[c](),g=h&&Ab(d);h?(h.name=g,d[g]=h):W(1282);G[b+4*f>>2]=g}}
function Hb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=X.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=X.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":W(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:W(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)G[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(f){W(1280);A("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:W(1280);A("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}G[b>>2]=c}else W(1281)}function Ib(a){var b=sa(a)+1,c=Q(b);D(a,E,c,b);return c}
function Jb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Kb(a,b,c,d,f){a-=5120;a=1==a?E:4==a?G:6==a?H:5==a||28922==a?xa:wa;var h=31-Math.clz32(a.BYTES_PER_ELEMENT);return a.subarray(f>>h,f+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<h)+4-1&-4)>>h)}function Y(a){var b=X.xc;if(b){var c=b.$b[a];"number"===typeof c&&(b.$b[a]=c=X.getUniformLocation(b,b.vc[a]+(0<c?"["+c+"]":"")));return c}W(1282)}for(var Z=[],X,Lb=new Float32Array(288),Mb=0;288>Mb;++Mb)Z[Mb]=Lb.subarray(0,Mb+1);
var Sb={ka:function(){return 0},eb:function(){return 0},gb:function(){},cb:function(){z("")},T:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},ca:function(a,b,c){a=P(a);if(!a)return-4;a=eb(a);I[b>>3]=a.width;I[c>>3]=a.height;return 0},ab:function(a,b,c){E.copyWithin(a,b,b+c)},Ma:function(a,b){function c(d){M(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},bb:function(a){var b=E.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/
c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ja.grow(Math.min(2147483648,d)-ua.byteLength+65535>>>16);ya();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},W:function(a,b,c,d){fb(a,b,c,d,12,"blur");return 0},R:function(a,b,c){a=P(a);if(!a)return-4;a.width=b;a.height=c;return 0},X:function(a,b,c,d){fb(a,b,c,d,13,"focus");return 0},fa:function(a,b,c,d){gb(a,b,c,d,2,"keydown");return 0},da:function(a,b,c,d){gb(a,b,c,d,1,"keypress");return 0},ea:function(a,
b,c,d){gb(a,b,c,d,3,"keyup");return 0},pa:function(a,b,c,d){R(a,b,c,d,5,"mousedown");return 0},ia:function(a,b,c,d){R(a,b,c,d,33,"mouseenter");return 0},ha:function(a,b,c,d){R(a,b,c,d,34,"mouseleave");return 0},ja:function(a,b,c,d){R(a,b,c,d,8,"mousemove");return 0},oa:function(a,b,c,d){R(a,b,c,d,6,"mouseup");return 0},Z:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.ic||document.body.kc||document.body.jc))return-1;a=P(a);if(!a)return-4;ib(a,b,c,
d,"pointerlockchange");ib(a,b,c,d,"mozpointerlockchange");ib(a,b,c,d,"webkitpointerlockchange");ib(a,b,c,d,"mspointerlockchange");return 0},Y:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.ic||document.body.kc||document.body.jc))return-1;a=P(a);if(!a)return-4;jb(a,b,c,d,"pointerlockerror");jb(a,b,c,d,"mozpointerlockerror");jb(a,b,c,d,"webkitpointerlockerror");jb(a,b,c,d,"mspointerlockerror");return 0},Ya:function(a,b,c,d){kb(a,b,c,d);return 0},_:function(a,b,c,d){lb(a,
b,c,d,25,"touchcancel");return 0},$:function(a,b,c,d){lb(a,b,c,d,23,"touchend");return 0},aa:function(a,b,c,d){lb(a,b,c,d,24,"touchmove");return 0},ba:function(a,b,c,d){lb(a,b,c,d,22,"touchstart");return 0},V:function(a,b,c,d){mb(a,b,c,d,31,"webglcontextlost");return 0},U:function(a,b,c,d){mb(a,b,c,d,32,"webglcontextrestored");return 0},ga:function(a,b,c,d){a=P(a);return"undefined"!==typeof a.onwheel?(pb(a,b,c,d),0):-1},J:function(a,b){b>>=2;b={alpha:!!G[b],depth:!!G[b+1],stencil:!!G[b+2],antialias:!!G[b+
3],premultipliedAlpha:!!G[b+4],preserveDrawingBuffer:!!G[b+5],powerPreference:Fb[G[b+6]],failIfMajorPerformanceCaveat:!!G[b+7],Bc:G[b+8],Kc:G[b+9],lc:G[b+10],zc:G[b+11],Mc:G[b+12],Nc:G[b+13]};a=P(a);return!a||b.zc?0:Bb(a,b)},wb:function(a,b){a=xb[a];b=F(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&qb(X);"OES_vertex_array_object"==b&&rb(X);"WEBGL_draw_buffers"==b&&sb(X);"WEBGL_multi_draw"==b&&tb(X);return!!a.ec.getExtension(b)},Ja:function(a){a>>=2;for(var b=0;14>b;++b)G[a+
b]=0;G[a]=G[a+1]=G[a+3]=G[a+4]=G[a+8]=G[a+10]=1},va:function(a){Eb=xb[a];e.Ec=X=Eb&&Eb.ec;return!a||X?0:-5},la:function(){return 0},db:function(a,b,c,d){a=Oa.Ic(a);b=Oa.Gc(a,b,c);G[d>>2]=b;return 0},$a:function(){},fb:function(a,b,c,d){for(var f=0,h=0;h<c;h++){var g=G[b>>2],m=G[b+4>>2];b+=8;for(var n=0;n<m;n++){var p=E[g+n],r=Na[a];0===p||10===p?((1===a?ia:A)(ra(r,0)),r.length=0):r.push(p)}f+=m}G[d>>2]=f;return 0},b:function(a){X.activeTexture(a)},I:function(a,b){X.attachShader(S[a],V[b])},c:function(a,
b){X.bindBuffer(a,vb[b])},h:function(a,b){X.bindFramebuffer(a,wb[b])},Ga:function(a,b){X.bindRenderbuffer(a,T[b])},a:function(a,b){X.bindTexture(a,U[b])},N:function(a,b,c,d){X.blendColor(a,b,c,d)},O:function(a,b){X.blendEquationSeparate(a,b)},P:function(a,b,c,d){X.blendFuncSeparate(a,b,c,d)},Ia:function(a,b,c,d){X.bufferData(a,c?E.subarray(c,c+b):b,d)},k:function(a,b,c,d){X.bufferSubData(a,b,E.subarray(d,d+c))},p:function(a){return X.checkFramebufferStatus(a)},tb:function(a){X.clear(a)},vb:function(a,
b,c,d){X.clearColor(a,b,c,d)},sa:function(a){X.clearDepth(a)},ub:function(a){X.clearStencil(a)},r:function(a,b,c,d){X.colorMask(!!a,!!b,!!c,!!d)},wa:function(a){X.compileShader(V[a])},Da:function(a,b,c,d,f,h,g,m){X.compressedTexImage2D(a,b,c,d,f,h,m?E.subarray(m,m+g):null)},Ba:function(){var a=Ab(S),b=X.createProgram();b.name=a;b.dc=b.bc=b.cc=0;b.hc=1;S[a]=b;return a},ya:function(a){var b=Ab(V);V[b]=X.createShader(a);return b},K:function(a){X.cullFace(a)},Pa:function(a,b){for(var c=0;c<a;c++){var d=
G[b+4*c>>2],f=vb[d];f&&(X.deleteBuffer(f),f.name=0,vb[d]=null)}},d:function(a,b){for(var c=0;c<a;++c){var d=G[b+4*c>>2],f=wb[d];f&&(X.deleteFramebuffer(f),f.name=0,wb[d]=null)}},u:function(a){if(a){var b=S[a];b?(X.deleteProgram(b),b.name=0,S[a]=null):W(1281)}},S:function(a,b){for(var c=0;c<a;c++){var d=G[b+4*c>>2],f=T[d];f&&(X.deleteRenderbuffer(f),f.name=0,T[d]=null)}},A:function(a){if(a){var b=V[a];b?(X.deleteShader(b),V[a]=null):W(1281)}},Oa:function(a,b){for(var c=0;c<a;c++){var d=G[b+4*c>>2],
f=U[d];f&&(X.deleteTexture(f),f.name=0,U[d]=null)}},D:function(a){X.depthFunc(a)},C:function(a){X.depthMask(!!a)},e:function(a){X.disable(a)},Q:function(a){X.disableVertexAttribArray(a)},y:function(a,b,c){X.drawArrays(a,b,c)},z:function(a,b,c,d){X.drawElements(a,b,c,d)},i:function(a){X.enable(a)},qb:function(a){X.enableVertexAttribArray(a)},m:function(a,b,c,d){X.framebufferRenderbuffer(a,b,c,T[d])},g:function(a,b,c,d,f){X.framebufferTexture2D(a,b,c,U[d],f)},L:function(a){X.frontFace(a)},Ka:function(a,
b){Gb(a,b,"createBuffer",vb)},q:function(a,b){Gb(a,b,"createFramebuffer",wb)},Ha:function(a,b){Gb(a,b,"createRenderbuffer",T)},Ea:function(a,b){Gb(a,b,"createTexture",U)},ta:function(a,b){return X.getAttribLocation(S[a],F(b))},f:function(a,b){Hb(a,b)},za:function(a,b,c,d){a=X.getProgramInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,E,d,b):0;c&&(G[c>>2]=b)},H:function(a,b,c){if(c)if(a>=ub)W(1281);else if(a=S[a],35716==b)a=X.getProgramInfoLog(a),null===a&&(a="(unknown error)"),G[c>>2]=a.length+
1;else if(35719==b){if(!a.dc)for(b=0;b<X.getProgramParameter(a,35718);++b)a.dc=Math.max(a.dc,X.getActiveUniform(a,b).name.length+1);G[c>>2]=a.dc}else if(35722==b){if(!a.bc)for(b=0;b<X.getProgramParameter(a,35721);++b)a.bc=Math.max(a.bc,X.getActiveAttrib(a,b).name.length+1);G[c>>2]=a.bc}else if(35381==b){if(!a.cc)for(b=0;b<X.getProgramParameter(a,35382);++b)a.cc=Math.max(a.cc,X.getActiveUniformBlockName(a,b).length+1);G[c>>2]=a.cc}else G[c>>2]=X.getProgramParameter(a,b);else W(1281)},ua:function(a,
b,c,d){a=X.getShaderInfoLog(V[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,E,d,b):0;c&&(G[c>>2]=b)},F:function(a,b,c){c?35716==b?(a=X.getShaderInfoLog(V[a]),null===a&&(a="(unknown error)"),G[c>>2]=a?a.length+1:0):35720==b?(a=X.getShaderSource(V[a]),G[c>>2]=a?a.length+1:0):G[c>>2]=X.getShaderParameter(V[a],b):W(1281)},Qa:function(a){var b=yb[a];if(!b){switch(a){case 7939:b=X.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Ib(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=
X.getParameter(a))||W(1280);b=b&&Ib(b);break;case 7938:b=Ib("OpenGL ES 2.0 ("+X.getParameter(7938)+")");break;case 35724:b=X.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Ib(b);break;default:W(1280)}yb[a]=b}return b},t:function(a,b){b=F(b);if(a=S[a]){var c=a,d=c.$b,f=c.wc,h;if(!d)for(c.$b=d={},c.vc={},h=0;h<X.getProgramParameter(c,35718);++h){var g=X.getActiveUniform(c,h);var m=g.name;
g=g.size;var n=Jb(m);n=0<n?m.slice(0,n):m;var p=c.hc;c.hc+=g;f[n]=[g,p];for(m=0;m<g;++m)d[p]=m,c.vc[p++]=n}c=a.$b;d=0;f=b;h=Jb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,f=b.slice(0,h));if((f=a.wc[f])&&d<f[0]&&(d+=f[1],c[d]=c[d]||X.getUniformLocation(a,b)))return d}else W(1281);return-1},Aa:function(a){a=S[a];X.linkProgram(a);a.$b=0;a.wc={}},M:function(a,b){X.polygonOffset(a,b)},Fa:function(a,b,c,d){X.renderbufferStorage(a,b,c,d)},s:function(a,b,c,d){X.scissor(a,b,c,d)},xa:function(a,b,c,d){for(var f=
"",h=0;h<b;++h){var g=d?G[d+4*h>>2]:-1;f+=F(G[c+4*h>>2],0>g?void 0:g)}X.shaderSource(V[a],f)},Na:function(a,b,c){X.stencilFunc(a,b,c)},ra:function(a,b,c,d){X.stencilFuncSeparate(a,b,c,d)},B:function(a){X.stencilMask(a)},La:function(a,b,c){X.stencilOp(a,b,c)},qa:function(a,b,c,d){X.stencilOpSeparate(a,b,c,d)},Ca:function(a,b,c,d,f,h,g,m,n){X.texImage2D(a,b,c,d,f,h,g,m,n?Kb(m,g,d,f,n):null)},j:function(a,b,c){X.texParameteri(a,b,c)},kb:function(a,b,c,d,f,h,g,m,n){var p=null;n&&(p=Kb(m,g,f,h,n));X.texSubImage2D(a,
b,c,d,f,h,g,m,p)},pb:function(a,b,c){if(288>=b)for(var d=Z[b-1],f=0;f<b;++f)d[f]=H[c+4*f>>2];else d=H.subarray(c>>2,c+4*b>>2);X.uniform1fv(Y(a),d)},G:function(a,b){X.uniform1i(Y(a),b)},ob:function(a,b,c){if(144>=b)for(var d=Z[2*b-1],f=0;f<2*b;f+=2)d[f]=H[c+4*f>>2],d[f+1]=H[c+(4*f+4)>>2];else d=H.subarray(c>>2,c+8*b>>2);X.uniform2fv(Y(a),d)},nb:function(a,b,c){if(96>=b)for(var d=Z[3*b-1],f=0;f<3*b;f+=3)d[f]=H[c+4*f>>2],d[f+1]=H[c+(4*f+4)>>2],d[f+2]=H[c+(4*f+8)>>2];else d=H.subarray(c>>2,c+12*b>>2);
X.uniform3fv(Y(a),d)},mb:function(a,b,c){if(72>=b){var d=Z[4*b-1],f=H;c>>=2;for(var h=0;h<4*b;h+=4){var g=c+h;d[h]=f[g];d[h+1]=f[g+1];d[h+2]=f[g+2];d[h+3]=f[g+3]}}else d=H.subarray(c>>2,c+16*b>>2);X.uniform4fv(Y(a),d)},lb:function(a,b,c,d){if(18>=b){var f=Z[16*b-1],h=H;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;f[g]=h[m];f[g+1]=h[m+1];f[g+2]=h[m+2];f[g+3]=h[m+3];f[g+4]=h[m+4];f[g+5]=h[m+5];f[g+6]=h[m+6];f[g+7]=h[m+7];f[g+8]=h[m+8];f[g+9]=h[m+9];f[g+10]=h[m+10];f[g+11]=h[m+11];f[g+12]=h[m+12];f[g+13]=
h[m+13];f[g+14]=h[m+14];f[g+15]=h[m+15]}}else f=H.subarray(d>>2,d+64*b>>2);X.uniformMatrix4fv(Y(a),!!c,f)},n:function(a){a=S[a];X.useProgram(a);X.xc=a},rb:function(a,b){X.vertexAttribDivisor(a,b)},sb:function(a,b,c,d,f,h){X.vertexAttribPointer(a,b,c,!!d,f,h)},l:function(a,b,c,d){X.viewport(a,b,c,d)},_a:function(){e.pc=function(a){0!=Nb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",e.pc)},Za:function(){e.uc=function(a){a=a.clipboardData.getData("text");ma("_sapp_emsc_onpaste",
["string"],[a])};window.addEventListener("paste",e.uc)},Xa:function(a){e.Oc=[];a=F(a);a=document.getElementById(a);e.qc=function(b){b.stopPropagation();b.preventDefault()};e.rc=function(b){b.stopPropagation();b.preventDefault()};e.sc=function(b){b.stopPropagation();b.preventDefault()};e.tc=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;e.Pc=c;Ob(c.length);var d;for(d=0;d<c.length;d++)ma("_sapp_emsc_drop",["number","string"],[d,c[d].name]);Pb(b.clientX,b.clientY)};a.addEventListener("dragenter",
e.qc,!1);a.addEventListener("dragleave",e.rc,!1);a.addEventListener("dragover",e.sc,!1);a.addEventListener("drop",e.tc,!1)},Sa:function(){var a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},x:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Qb()});document.body.append(a)},w:function(){document.getElementById("_sokol_app_input_element").focus()},xb:function(a){a=
F(a);e.Zb=document.getElementById(a);e.Zb||console.log("sokol_app.h: invalid target:"+a);e.Zb.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Wa:function(){window.removeEventListener("beforeunload",e.pc)},Va:function(){window.removeEventListener("paste",e.uc)},Ua:function(a){a=F(a);a=document.getElementById(a);a.removeEventListener("dragenter",e.qc);a.removeEventListener("dragleave",e.rc);a.removeEventListener("dragover",e.sc);a.removeEventListener("drop",
e.tc)},E:function(){e.Zb&&e.Zb.requestPointerLock&&e.Zb.requestPointerLock()},Ra:function(a,b,c){var d=document.createElement("canvas");d.width=a;d.height=b;var f=d.getContext("2d"),h=f.createImageData(a,b);h.data.set(E.subarray(c,c+a*b*4));f.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},v:function(){document.getElementById("_sokol_app_input_element").blur()},Ta:function(a){a=F(a);var b=document.createElement("textarea");
b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},hb:function(){return e.Yb?e.Yb.bufferSize:0},jb:function(a,b,c){e.Tb=null;e.Yb=null;"undefined"!==typeof AudioContext?e.Tb=new AudioContext({sampleRate:a,latencyHint:"interactive"}):
"undefined"!==typeof webkitAudioContext?e.Tb=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}):(e.Tb=null,console.log("sokol_audio.h: no WebAudio support"));return e.Tb?(console.log("sokol_audio.h: sample rate ",e.Tb.sampleRate),e.Yb=e.Tb.createScriptProcessor(c,0,b),e.Yb.onaudioprocess=function(d){var f=d.outputBuffer.length,h=Rb(f);if(h)for(var g=d.outputBuffer.numberOfChannels,m=0;m<g;m++)for(var n=d.outputBuffer.getChannelData(m),p=0;p<f;p++)n[p]=H[(h>>2)+(g*p+m)]},e.Yb.connect(e.Tb.destination),
a=function(){e.Tb&&"suspended"===e.Tb.state&&e.Tb.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},ib:function(){return e.Tb?e.Tb.sampleRate:0},na:function(){null!==e.Tb&&(e.Yb&&e.Yb.disconnect(),e.Tb.close(),e.Tb=null,e.Yb=null)},ma:function(){return navigator.userAgent.includes("Macintosh")?1:0},o:function(){return performance.now()}};
(function(){function a(f){e.asm=f.exports;ja=e.asm.yb;ya();za=e.asm.Sb;Ba.unshift(e.asm.zb);J--;e.monitorRunDependencies&&e.monitorRunDependencies(J);0==J&&(null!==Ga&&(clearInterval(Ga),Ga=null),K&&(f=K,K=null,f()))}function b(f){a(f.instance)}function c(f){return Ka().then(function(h){return WebAssembly.instantiate(h,d)}).then(function(h){return h}).then(f,function(h){A("failed to asynchronously prepare wasm: "+h);z(h)})}var d={a:Sb};J++;e.monitorRunDependencies&&e.monitorRunDependencies(J);if(e.instantiateWasm)try{return e.instantiateWasm(d,
a)}catch(f){return A("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return B||"function"!==typeof WebAssembly.instantiateStreaming||Ha()||L.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(L,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(h){A("wasm streaming compile failed: "+h);A("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.zb).apply(null,arguments)};var Qb=e.__sapp_emsc_notify_keyboard_hidden=function(){return(Qb=e.__sapp_emsc_notify_keyboard_hidden=e.asm.Ab).apply(null,arguments)};e.__sapp_emsc_onpaste=function(){return(e.__sapp_emsc_onpaste=e.asm.Bb).apply(null,arguments)};
var Nb=e.__sapp_html5_get_ask_leave_site=function(){return(Nb=e.__sapp_html5_get_ask_leave_site=e.asm.Cb).apply(null,arguments)},Ob=e.__sapp_emsc_begin_drop=function(){return(Ob=e.__sapp_emsc_begin_drop=e.asm.Db).apply(null,arguments)};e.__sapp_emsc_drop=function(){return(e.__sapp_emsc_drop=e.asm.Eb).apply(null,arguments)};var Pb=e.__sapp_emsc_end_drop=function(){return(Pb=e.__sapp_emsc_end_drop=e.asm.Fb).apply(null,arguments)};
e.__sapp_emsc_invoke_fetch_cb=function(){return(e.__sapp_emsc_invoke_fetch_cb=e.asm.Gb).apply(null,arguments)};e._main=function(){return(e._main=e.asm.Hb).apply(null,arguments)};var Rb=e.__saudio_emsc_pull=function(){return(Rb=e.__saudio_emsc_pull=e.asm.Ib).apply(null,arguments)};e.__sargs_add_kvp=function(){return(e.__sargs_add_kvp=e.asm.Jb).apply(null,arguments)};e.__sfetch_emsc_head_response=function(){return(e.__sfetch_emsc_head_response=e.asm.Kb).apply(null,arguments)};
e.__sfetch_emsc_get_response=function(){return(e.__sfetch_emsc_get_response=e.asm.Lb).apply(null,arguments)};e.__sfetch_emsc_failed_http_status=function(){return(e.__sfetch_emsc_failed_http_status=e.asm.Mb).apply(null,arguments)};e.__sfetch_emsc_failed_buffer_too_small=function(){return(e.__sfetch_emsc_failed_buffer_too_small=e.asm.Nb).apply(null,arguments)};
var Q=e._malloc=function(){return(Q=e._malloc=e.asm.Ob).apply(null,arguments)},oa=e.stackSave=function(){return(oa=e.stackSave=e.asm.Pb).apply(null,arguments)},pa=e.stackRestore=function(){return(pa=e.stackRestore=e.asm.Qb).apply(null,arguments)},C=e.stackAlloc=function(){return(C=e.stackAlloc=e.asm.Rb).apply(null,arguments)},Tb;function fa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}K=function Ub(){Tb||Vb();Tb||(K=Ub)};
function Vb(a){function b(){if(!Tb&&(Tb=!0,e.calledRun=!0,!ka)){La(Ba);La(Ca);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(Wb){var c=a,d=e._main;c=c||[];var f=c.length+1,h=C(4*(f+1));G[h>>2]=ta(ba);for(var g=1;g<f;g++)G[(h>>2)+g]=ta(c[g-1]);G[(h>>2)+f]=0;try{var m=d(f,h);if(!(noExitRuntime||0<ha)){if(e.onExit)e.onExit(m);ka=!0}q(m,new fa(m))}catch(n){n instanceof fa||"unwind"==n||q(1,n)}finally{}}if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)c=e.postRun.shift(),
Ea.unshift(c);La(Ea)}}a=a||aa;if(!(0<J)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Fa();La(Aa);0<J||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);b()},1)):b())}}e.run=Vb;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Wb=!0;e.noInitialRun&&(Wb=!1);Vb();
