
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var k={},l;for(l in f)f.hasOwnProperty(l)&&(k[l]=f[l]);var aa=[],ba="./this.program";function q(a,b){throw b;}var ca="object"===typeof window,u="function"===typeof importScripts,v="",da,w,ea,x,y;
if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)v=u?require("path").dirname(v)+"/":__dirname+"/",da=function(a,b){x||(x=require("fs"));y||(y=require("path"));a=y.normalize(a);return x.readFileSync(a,b?null:"utf8")},ea=function(a){a=da(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||z("Assertion failed: undefined");return a},w=function(a,b,c){x||(x=require("fs"));y||(y=require("path"));a=y.normalize(a);x.readFile(a,function(d,e){d?c(d):b(e.buffer)})},
1<process.argv.length&&(ba=process.argv[1].replace(/\\/g,"/")),aa=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof fa))throw a;}),process.on("unhandledRejection",function(a){throw a;}),q=function(a,b){if(noExitRuntime||0<ha)throw process.exitCode=a,b;b instanceof fa||A("exiting due to exception: "+b);process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(ca||u)u?v=self.location.href:"undefined"!==
typeof document&&document.currentScript&&(v=document.currentScript.src),v=0!==v.indexOf("blob:")?v.substr(0,v.replace(/[?#].*/,"").lastIndexOf("/")+1):"",da=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},u&&(ea=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),w=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==
d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ia=f.print||console.log.bind(console),A=f.printErr||console.warn.bind(console);for(l in k)k.hasOwnProperty(l)&&(f[l]=k[l]);k=null;f.arguments&&(aa=f.arguments);f.thisProgram&&(ba=f.thisProgram);f.quit&&(q=f.quit);var B;f.wasmBinary&&(B=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!==typeof WebAssembly&&z("no native wasm support detected");var ja,ka=!1;
function la(a){var b=f["_"+a];b||z("Assertion failed: Cannot call unknown function "+(a+", make sure it is exported"));return b}function ma(a,b,c){var d={string:function(n){var p=0;if(null!==n&&void 0!==n&&0!==n){var r=(n.length<<2)+1;p=C(r);D(n,E,p,r)}return p},array:function(n){var p=C(n.length);na.set(n,p);return p}};a=la(a);var e=[],h=0;if(c)for(var g=0;g<c.length;g++){var m=d[b[g]];m?(0===h&&(h=oa()),e[g]=m(c[g])):e[g]=c[g]}b=a.apply(null,e);b=function(n){0!==h&&pa(h);return n}(b)}
var qa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ra(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&qa)return qa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function F(a,b){return a?ra(E,a,b):""}
function D(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var m=a.charCodeAt(++h);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}
function sa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function ta(a){var b=sa(a)+1,c=C(b);D(a,na,c,b);return c}var ua,na,E,va,wa,G,xa,H,I;
function ya(){var a=ja.buffer;ua=a;f.HEAP8=na=new Int8Array(a);f.HEAP16=va=new Int16Array(a);f.HEAP32=G=new Int32Array(a);f.HEAPU8=E=new Uint8Array(a);f.HEAPU16=wa=new Uint16Array(a);f.HEAPU32=xa=new Uint32Array(a);f.HEAPF32=H=new Float32Array(a);f.HEAPF64=I=new Float64Array(a)}var za,Aa=[],Ba=[],Ca=[],Da=[],Ea=[],ha=0;function Fa(){var a=f.preRun.shift();Aa.unshift(a)}var J=0,Ga=null,K=null;f.preloadedImages={};f.preloadedAudios={};
function z(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";A(a);ka=!0;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function Ha(){return L.startsWith("data:application/octet-stream;base64,")}var L;L="z9001-ui.wasm";if(!Ha()){var Ia=L;L=f.locateFile?f.locateFile(Ia,v):v+Ia}function Ja(){var a=L;try{if(a==L&&B)return new Uint8Array(B);if(ea)return ea(a);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
function Ka(){if(!B&&(ca||u)){if("function"===typeof fetch&&!L.startsWith("file://"))return fetch(L,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+L+"'";return a.arrayBuffer()}).catch(function(){return Ja()});if(w)return new Promise(function(a,b){w(L,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ja()})}
function La(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.Nc;"number"===typeof c?void 0===b.lc?M(c)():M(c)(b.lc):c(void 0===b.lc?null:b.lc)}}}var Ma=[];function M(a){var b=Ma[a];b||(a>=Ma.length&&(Ma.length=a+1),Ma[a]=b=za.get(a));return b}var Na=[null,[],[]],Oa={},Pa=0;function Qa(){for(var a=N.length-1;0<=a;--a)Ra(a);N=[];Sa=[]}var Sa=[];function Ta(){if(Pa&&Ua.fc)for(var a=0;a<Sa.length;++a){var b=Sa[a];Sa.splice(a,1);--a;b.Vc.apply(null,b.Jc)}}var N=[];
function Ra(a){var b=N[a];b.target.removeEventListener(b.Zb,b.Ec,b.$b);N.splice(a,1)}function O(a){function b(d){++Pa;Ua=a;Ta();a.bc(d);Ta();--Pa}if(a.ac)a.Ec=b,a.target.addEventListener(a.Zb,b,a.$b),N.push(a),Va||(Da.push(Qa),Va=!0);else for(var c=0;c<N.length;++c)N[c].target==a.target&&N[c].Zb==a.Zb&&Ra(c--)}function Wa(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
var Va,Ua,Xa,Ya,Za,$a,ab,bb,cb,db=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function P(a){a=2<a?F(a):a;return db[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function eb(a){return 0>db.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function fb(a,b,c,d,e,h){Xa||(Xa=Q(256));a={target:P(a),Zb:h,ac:d,bc:function(g){g=g||event;var m=g.target.id?g.target.id:"",n=Xa;D(Wa(g.target),E,n+0,128);D(m,E,n+128,128);M(d)(e,n,b)&&g.preventDefault()},$b:c};O(a)}
function gb(a,b,c,d,e,h){Ya||(Ya=Q(176));a={target:P(a),fc:!0,Zb:h,ac:d,bc:function(g){var m=Ya;I[m>>3]=g.timeStamp;var n=m>>2;G[n+2]=g.location;G[n+3]=g.ctrlKey;G[n+4]=g.shiftKey;G[n+5]=g.altKey;G[n+6]=g.metaKey;G[n+7]=g.repeat;G[n+8]=g.charCode;G[n+9]=g.keyCode;G[n+10]=g.which;D(g.key||"",E,m+44,32);D(g.code||"",E,m+76,32);D(g.char||"",E,m+108,32);D(g.locale||"",E,m+140,32);M(d)(e,m,b)&&g.preventDefault()},$b:c};O(a)}
function hb(a,b,c){I[a>>3]=b.timeStamp;a>>=2;G[a+2]=b.screenX;G[a+3]=b.screenY;G[a+4]=b.clientX;G[a+5]=b.clientY;G[a+6]=b.ctrlKey;G[a+7]=b.shiftKey;G[a+8]=b.altKey;G[a+9]=b.metaKey;va[2*a+20]=b.button;va[2*a+21]=b.buttons;G[a+11]=b.movementX;G[a+12]=b.movementY;c=eb(c);G[a+13]=b.clientX-c.left;G[a+14]=b.clientY-c.top}
function R(a,b,c,d,e,h){Za||(Za=Q(72));a=P(a);O({target:a,fc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Zb:h,ac:d,bc:function(g){g=g||event;hb(Za,g,a);M(d)(e,Za,b)&&g.preventDefault()},$b:c})}function ib(a,b,c,d,e){$a||($a=Q(260));O({target:a,Zb:e,ac:d,bc:function(h){h=h||event;var g=$a,m=document.pointerLockElement||document.pc||document.oc||document.qc;G[g>>2]=!!m;var n=m&&m.id?m.id:"";D(Wa(m),E,g+4,128);D(n,E,g+132,128);M(d)(20,g,b)&&h.preventDefault()},$b:c})}
function jb(a,b,c,d,e){O({target:a,Zb:e,ac:d,bc:function(h){h=h||event;M(d)(38,0,b)&&h.preventDefault()},$b:c})}
function kb(a,b,c,d){ab||(ab=Q(36));a=P(a);O({target:a,Zb:"resize",ac:d,bc:function(e){e=e||event;if(e.target==a){var h=document.body;if(h){var g=ab;G[g>>2]=e.detail;G[g+4>>2]=h.clientWidth;G[g+8>>2]=h.clientHeight;G[g+12>>2]=innerWidth;G[g+16>>2]=innerHeight;G[g+20>>2]=outerWidth;G[g+24>>2]=outerHeight;G[g+28>>2]=pageXOffset;G[g+32>>2]=pageYOffset;M(d)(10,g,b)&&e.preventDefault()}}},$b:c})}
function lb(a,b,c,d,e,h){bb||(bb=Q(1696));a=P(a);O({target:a,fc:"touchstart"==h||"touchend"==h,Zb:h,ac:d,bc:function(g){for(var m,n={},p=g.touches,r=0;r<p.length;++r)m=p[r],m.tc=m.uc=0,n[m.identifier]=m;for(r=0;r<g.changedTouches.length;++r)m=g.changedTouches[r],m.tc=1,n[m.identifier]=m;for(r=0;r<g.targetTouches.length;++r)n[g.targetTouches[r].identifier].uc=1;p=bb;I[p>>3]=g.timeStamp;var t=p>>2;G[t+3]=g.ctrlKey;G[t+4]=g.shiftKey;G[t+5]=g.altKey;G[t+6]=g.metaKey;t+=7;var pb=eb(a),qb=0;for(r in n)if(m=
n[r],G[t]=m.identifier,G[t+1]=m.screenX,G[t+2]=m.screenY,G[t+3]=m.clientX,G[t+4]=m.clientY,G[t+5]=m.pageX,G[t+6]=m.pageY,G[t+7]=m.tc,G[t+8]=m.uc,G[t+9]=m.clientX-pb.left,G[t+10]=m.clientY-pb.top,t+=13,31<++qb)break;G[p+8>>2]=qb;M(d)(e,p,b)&&g.preventDefault()},$b:c})}function mb(a,b,c,d,e,h){a={target:P(a),Zb:h,ac:d,bc:function(g){g=g||event;M(d)(e,0,b)&&g.preventDefault()},$b:c};O(a)}
function nb(a,b,c,d){cb||(cb=Q(104));O({target:a,fc:!0,Zb:"wheel",ac:d,bc:function(e){e=e||event;var h=cb;hb(h,e,a);I[h+72>>3]=e.deltaX;I[h+80>>3]=e.deltaY;I[h+88>>3]=e.deltaZ;G[h+96>>2]=e.deltaMode;M(d)(9,h,b)&&e.preventDefault()},$b:c})}
function ob(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,h){b.drawArraysInstancedANGLE(c,d,e,h)},a.drawElementsInstanced=function(c,d,e,h,g){b.drawElementsInstancedANGLE(c,d,e,h,g)})}
function rb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function sb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function tb(a){a.Rc=a.getExtension("WEBGL_multi_draw")}
var ub=1,vb=[],S=[],wb=[],T=[],U=[],V=[],xb=[],yb={};function W(a){zb||(zb=a)}function Ab(a){for(var b=ub++,c=a.length;c<b;c++)a[c]=null;return b}function Bb(a,b){a.sc||(a.sc=a.getContext,a.getContext=function(d,e){e=a.sc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Cb(c,b):0}function Cb(a,b){var c=Ab(xb),d={Pc:c,attributes:b,version:b.Hc,kc:a};a.canvas&&(a.canvas.Ic=d);xb[c]=d;("undefined"===typeof b.rc||b.rc)&&Db(d);return c}
function Db(a){a||(a=Eb);if(!a.Gc){a.Gc=!0;var b=a.kc;ob(b);rb(b);sb(b);b.Lc=b.getExtension("EXT_disjoint_timer_query");tb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var zb,Eb,Fb=["default","low-power","high-performance"];function Gb(a,b,c,d){for(var e=0;e<a;e++){var h=X[c](),g=h&&Ab(d);h?(h.name=g,d[g]=h):W(1282);G[b+4*e>>2]=g}}
function Hb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=X.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=X.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":W(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:W(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)G[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){W(1280);A("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:W(1280);A("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}G[b>>2]=c}else W(1281)}function Ib(a){var b=sa(a)+1,c=Q(b);D(a,E,c,b);return c}
function Jb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Kb(a,b,c,d,e){a-=5120;a=1==a?E:4==a?G:6==a?H:5==a||28922==a?xa:wa;var h=31-Math.clz32(a.BYTES_PER_ELEMENT);return a.subarray(e>>h,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<h)+4-1&-4)>>h)}function Y(a){var b=X.Dc;if(b){var c=b.ec[a];"number"===typeof c&&(b.ec[a]=c=X.getUniformLocation(b,b.Bc[a]+(0<c?"["+c+"]":"")));return c}W(1282)}for(var Z=[],X,Lb=new Float32Array(288),Mb=0;288>Mb;++Mb)Z[Mb]=Lb.subarray(0,Mb+1);
var Xb={ma:function(){return 0},gb:function(){return 0},jb:function(){},eb:function(){z("")},L:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},S:function(a,b,c){a=P(a);if(!a)return-4;a=eb(a);I[b>>3]=a.width;I[c>>3]=a.height;return 0},cb:function(a,b,c){E.copyWithin(a,b,b+c)},Ab:function(a,b){function c(d){M(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},db:function(a){var b=E.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/
c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ja.grow(Math.min(2147483648,d)-ua.byteLength+65535>>>16);ya();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},X:function(a,b,c,d){fb(a,b,c,d,12,"blur");return 0},I:function(a,b,c){a=P(a);if(!a)return-4;a.width=b;a.height=c;return 0},Y:function(a,b,c,d){fb(a,b,c,d,13,"focus");return 0},fa:function(a,b,c,d){gb(a,b,c,d,2,"keydown");return 0},da:function(a,b,c,d){gb(a,b,c,d,1,"keypress");return 0},ea:function(a,
b,c,d){gb(a,b,c,d,3,"keyup");return 0},la:function(a,b,c,d){R(a,b,c,d,5,"mousedown");return 0},ia:function(a,b,c,d){R(a,b,c,d,33,"mouseenter");return 0},ha:function(a,b,c,d){R(a,b,c,d,34,"mouseleave");return 0},ja:function(a,b,c,d){R(a,b,c,d,8,"mousemove");return 0},ka:function(a,b,c,d){R(a,b,c,d,6,"mouseup");return 0},_:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.pc||document.body.oc||document.body.qc))return-1;a=P(a);if(!a)return-4;ib(a,b,c,
d,"pointerlockchange");ib(a,b,c,d,"mozpointerlockchange");ib(a,b,c,d,"webkitpointerlockchange");ib(a,b,c,d,"mspointerlockchange");return 0},Z:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.pc||document.body.oc||document.body.qc))return-1;a=P(a);if(!a)return-4;jb(a,b,c,d,"pointerlockerror");jb(a,b,c,d,"mozpointerlockerror");jb(a,b,c,d,"webkitpointerlockerror");jb(a,b,c,d,"mspointerlockerror");return 0},La:function(a,b,c,d){kb(a,b,c,d);return 0},$:function(a,b,c,d){lb(a,
b,c,d,25,"touchcancel");return 0},aa:function(a,b,c,d){lb(a,b,c,d,23,"touchend");return 0},ba:function(a,b,c,d){lb(a,b,c,d,24,"touchmove");return 0},ca:function(a,b,c,d){lb(a,b,c,d,22,"touchstart");return 0},W:function(a,b,c,d){mb(a,b,c,d,31,"webglcontextlost");return 0},V:function(a,b,c,d){mb(a,b,c,d,32,"webglcontextrestored");return 0},ga:function(a,b,c,d){a=P(a);return"undefined"!==typeof a.onwheel?(nb(a,b,c,d),0):-1},ra:function(a,b){b>>=2;b={alpha:!!G[b],depth:!!G[b+1],stencil:!!G[b+2],antialias:!!G[b+
3],premultipliedAlpha:!!G[b+4],preserveDrawingBuffer:!!G[b+5],powerPreference:Fb[G[b+6]],failIfMajorPerformanceCaveat:!!G[b+7],Hc:G[b+8],Qc:G[b+9],rc:G[b+10],Fc:G[b+11],Sc:G[b+12],Tc:G[b+13]};a=P(a);return!a||b.Fc?0:Bb(a,b)},ab:function(a,b){a=xb[a];b=F(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&ob(X);"OES_vertex_array_object"==b&&rb(X);"WEBGL_draw_buffers"==b&&sb(X);"WEBGL_multi_draw"==b&&tb(X);return!!a.kc.getExtension(b)},wb:function(a){a>>=2;for(var b=0;14>b;++b)G[a+
b]=0;G[a]=G[a+1]=G[a+3]=G[a+4]=G[a+8]=G[a+10]=1},hb:function(a){Eb=xb[a];f.Kc=X=Eb&&Eb.kc;return!a||X?0:-5},na:function(){return 0},fb:function(a,b,c,d){a=Oa.Oc(a);b=Oa.Mc(a,b,c);G[d>>2]=b;return 0},bb:function(){},ib:function(a,b,c,d){for(var e=0,h=0;h<c;h++){var g=G[b>>2],m=G[b+4>>2];b+=8;for(var n=0;n<m;n++){var p=E[g+n],r=Na[a];0===p||10===p?((1===a?ia:A)(ra(r,0)),r.length=0):r.push(p)}e+=m}G[d>>2]=e;return 0},b:function(a){X.activeTexture(a)},K:function(a,b){X.attachShader(S[a],V[b])},c:function(a,
b){X.bindBuffer(a,vb[b])},g:function(a,b){X.bindFramebuffer(a,wb[b])},Ha:function(a,b){X.bindRenderbuffer(a,T[b])},a:function(a,b){X.bindTexture(a,U[b])},P:function(a,b,c,d){X.blendColor(a,b,c,d)},Q:function(a,b){X.blendEquationSeparate(a,b)},R:function(a,b,c,d){X.blendFuncSeparate(a,b,c,d)},Ja:function(a,b,c,d){X.bufferData(a,c?E.subarray(c,c+b):b,d)},k:function(a,b,c,d){X.bufferSubData(a,b,E.subarray(d,d+c))},r:function(a){return X.checkFramebufferStatus(a)},xb:function(a){X.clear(a)},zb:function(a,
b,c,d){X.clearColor(a,b,c,d)},ua:function(a){X.clearDepth(a)},yb:function(a){X.clearStencil(a)},q:function(a,b,c,d){X.colorMask(!!a,!!b,!!c,!!d)},xa:function(a){X.compileShader(V[a])},Ea:function(a,b,c,d,e,h,g,m){X.compressedTexImage2D(a,b,c,d,e,h,m?E.subarray(m,m+g):null)},Ca:function(){var a=Ab(S),b=X.createProgram();b.name=a;b.jc=b.hc=b.ic=0;b.nc=1;S[a]=b;return a},za:function(a){var b=Ab(V);V[b]=X.createShader(a);return b},M:function(a){X.cullFace(a)},Qa:function(a,b){for(var c=0;c<a;c++){var d=
G[b+4*c>>2],e=vb[d];e&&(X.deleteBuffer(e),e.name=0,vb[d]=null)}},d:function(a,b){for(var c=0;c<a;++c){var d=G[b+4*c>>2],e=wb[d];e&&(X.deleteFramebuffer(e),e.name=0,wb[d]=null)}},t:function(a){if(a){var b=S[a];b?(X.deleteProgram(b),b.name=0,S[a]=null):W(1281)}},U:function(a,b){for(var c=0;c<a;c++){var d=G[b+4*c>>2],e=T[d];e&&(X.deleteRenderbuffer(e),e.name=0,T[d]=null)}},A:function(a){if(a){var b=V[a];b?(X.deleteShader(b),V[a]=null):W(1281)}},Oa:function(a,b){for(var c=0;c<a;c++){var d=G[b+4*c>>2],
e=U[d];e&&(X.deleteTexture(e),e.name=0,U[d]=null)}},D:function(a){X.depthFunc(a)},C:function(a){X.depthMask(!!a)},e:function(a){X.disable(a)},T:function(a){X.disableVertexAttribArray(a)},x:function(a,b,c){X.drawArrays(a,b,c)},y:function(a,b,c,d){X.drawElements(a,b,c,d)},i:function(a){X.enable(a)},tb:function(a){X.enableVertexAttribArray(a)},l:function(a,b,c,d){X.framebufferRenderbuffer(a,b,c,T[d])},h:function(a,b,c,d,e){X.framebufferTexture2D(a,b,c,U[d],e)},N:function(a){X.frontFace(a)},Ka:function(a,
b){Gb(a,b,"createBuffer",vb)},p:function(a,b){Gb(a,b,"createFramebuffer",wb)},Ia:function(a,b){Gb(a,b,"createRenderbuffer",T)},Fa:function(a,b){Gb(a,b,"createTexture",U)},va:function(a,b){return X.getAttribLocation(S[a],F(b))},f:function(a,b){Hb(a,b)},Aa:function(a,b,c,d){a=X.getProgramInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,E,d,b):0;c&&(G[c>>2]=b)},J:function(a,b,c){if(c)if(a>=ub)W(1281);else if(a=S[a],35716==b)a=X.getProgramInfoLog(a),null===a&&(a="(unknown error)"),G[c>>2]=a.length+
1;else if(35719==b){if(!a.jc)for(b=0;b<X.getProgramParameter(a,35718);++b)a.jc=Math.max(a.jc,X.getActiveUniform(a,b).name.length+1);G[c>>2]=a.jc}else if(35722==b){if(!a.hc)for(b=0;b<X.getProgramParameter(a,35721);++b)a.hc=Math.max(a.hc,X.getActiveAttrib(a,b).name.length+1);G[c>>2]=a.hc}else if(35381==b){if(!a.ic)for(b=0;b<X.getProgramParameter(a,35382);++b)a.ic=Math.max(a.ic,X.getActiveUniformBlockName(a,b).length+1);G[c>>2]=a.ic}else G[c>>2]=X.getProgramParameter(a,b);else W(1281)},wa:function(a,
b,c,d){a=X.getShaderInfoLog(V[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,E,d,b):0;c&&(G[c>>2]=b)},G:function(a,b,c){c?35716==b?(a=X.getShaderInfoLog(V[a]),null===a&&(a="(unknown error)"),G[c>>2]=a?a.length+1:0):35720==b?(a=X.getShaderSource(V[a]),G[c>>2]=a?a.length+1:0):G[c>>2]=X.getShaderParameter(V[a],b):W(1281)},Ra:function(a){var b=yb[a];if(!b){switch(a){case 7939:b=X.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Ib(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=
X.getParameter(a))||W(1280);b=b&&Ib(b);break;case 7938:b=Ib("OpenGL ES 2.0 ("+X.getParameter(7938)+")");break;case 35724:b=X.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Ib(b);break;default:W(1280)}yb[a]=b}return b},s:function(a,b){b=F(b);if(a=S[a]){var c=a,d=c.ec,e=c.Cc,h;if(!d)for(c.ec=d={},c.Bc={},h=0;h<X.getProgramParameter(c,35718);++h){var g=X.getActiveUniform(c,h);var m=g.name;
g=g.size;var n=Jb(m);n=0<n?m.slice(0,n):m;var p=c.nc;c.nc+=g;e[n]=[g,p];for(m=0;m<g;++m)d[p]=m,c.Bc[p++]=n}c=a.ec;d=0;e=b;h=Jb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Cc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||X.getUniformLocation(a,b)))return d}else W(1281);return-1},Ba:function(a){a=S[a];X.linkProgram(a);a.ec=0;a.Cc={}},O:function(a,b){X.polygonOffset(a,b)},Ga:function(a,b,c,d){X.renderbufferStorage(a,b,c,d)},z:function(a,b,c,d){X.scissor(a,b,c,d)},ya:function(a,b,c,d){for(var e=
"",h=0;h<b;++h){var g=d?G[d+4*h>>2]:-1;e+=F(G[c+4*h>>2],0>g?void 0:g)}X.shaderSource(V[a],e)},Na:function(a,b,c){X.stencilFunc(a,b,c)},ta:function(a,b,c,d){X.stencilFuncSeparate(a,b,c,d)},B:function(a){X.stencilMask(a)},Ma:function(a,b,c){X.stencilOp(a,b,c)},sa:function(a,b,c,d){X.stencilOpSeparate(a,b,c,d)},Da:function(a,b,c,d,e,h,g,m,n){X.texImage2D(a,b,c,d,e,h,g,m,n?Kb(m,g,d,e,n):null)},j:function(a,b,c){X.texParameteri(a,b,c)},nb:function(a,b,c,d,e,h,g,m,n){var p=null;n&&(p=Kb(m,g,e,h,n));X.texSubImage2D(a,
b,c,d,e,h,g,m,p)},sb:function(a,b,c){if(288>=b)for(var d=Z[b-1],e=0;e<b;++e)d[e]=H[c+4*e>>2];else d=H.subarray(c>>2,c+4*b>>2);X.uniform1fv(Y(a),d)},H:function(a,b){X.uniform1i(Y(a),b)},rb:function(a,b,c){if(144>=b)for(var d=Z[2*b-1],e=0;e<2*b;e+=2)d[e]=H[c+4*e>>2],d[e+1]=H[c+(4*e+4)>>2];else d=H.subarray(c>>2,c+8*b>>2);X.uniform2fv(Y(a),d)},qb:function(a,b,c){if(96>=b)for(var d=Z[3*b-1],e=0;e<3*b;e+=3)d[e]=H[c+4*e>>2],d[e+1]=H[c+(4*e+4)>>2],d[e+2]=H[c+(4*e+8)>>2];else d=H.subarray(c>>2,c+12*b>>2);
X.uniform3fv(Y(a),d)},pb:function(a,b,c){if(72>=b){var d=Z[4*b-1],e=H;c>>=2;for(var h=0;h<4*b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=H.subarray(c>>2,c+16*b>>2);X.uniform4fv(Y(a),d)},ob:function(a,b,c,d){if(18>=b){var e=Z[16*b-1],h=H;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=h[m];e[g+1]=h[m+1];e[g+2]=h[m+2];e[g+3]=h[m+3];e[g+4]=h[m+4];e[g+5]=h[m+5];e[g+6]=h[m+6];e[g+7]=h[m+7];e[g+8]=h[m+8];e[g+9]=h[m+9];e[g+10]=h[m+10];e[g+11]=h[m+11];e[g+12]=h[m+12];e[g+13]=
h[m+13];e[g+14]=h[m+14];e[g+15]=h[m+15]}}else e=H.subarray(d>>2,d+64*b>>2);X.uniformMatrix4fv(Y(a),!!c,e)},m:function(a){a=S[a];X.useProgram(a);X.Dc=a},ub:function(a,b){X.vertexAttribDivisor(a,b)},vb:function(a,b,c,d,e,h){X.vertexAttribPointer(a,b,c,!!d,e,h)},o:function(a,b,c,d){X.viewport(a,b,c,d)},_a:function(){f.vc=function(a){0!=Nb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.vc)},Za:function(){f.Ac=function(a){a=a.clipboardData.getData("text");ma("_sapp_emsc_onpaste",
["string"],[a])};window.addEventListener("paste",f.Ac)},Ya:function(a){f.Uc=[];a=F(a);a=document.getElementById(a);f.wc=function(b){b.stopPropagation();b.preventDefault()};f.xc=function(b){b.stopPropagation();b.preventDefault()};f.yc=function(b){b.stopPropagation();b.preventDefault()};f.zc=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;f.mc=c;Ob(c.length);var d;for(d=0;d<c.length;d++)ma("_sapp_emsc_drop",["number","string"],[d,c[d].name]);Pb(b.clientX,b.clientY)};a.addEventListener("dragenter",
f.wc,!1);a.addEventListener("dragleave",f.xc,!1);a.addEventListener("dragover",f.yc,!1);a.addEventListener("drop",f.zc,!1)},Ta:function(){var a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},w:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Qb()});document.body.append(a)},Cb:function(a){return 0>a||a>=f.mc.length?0:f.mc[a].size},Bb:function(a,b,c,d,e){var h=
new FileReader;h.onload=function(g){g=g.target.result;g.byteLength>d?Rb(a,0,1,b,0,c,d,e):(E.set(new Uint8Array(g),c),Rb(a,1,0,b,g.byteLength,c,d,e))};h.onerror=function(){Rb(a,0,2,b,0,c,d,e)};h.readAsArrayBuffer(f.mc[a])},v:function(){document.getElementById("_sokol_app_input_element").focus()},Pa:function(a){a=F(a);f.dc=document.getElementById(a);f.dc||console.log("sokol_app.h: invalid target:"+a);f.dc.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},
Xa:function(){window.removeEventListener("beforeunload",f.vc)},Wa:function(){window.removeEventListener("paste",f.Ac)},Va:function(a){a=F(a);a=document.getElementById(a);a.removeEventListener("dragenter",f.wc);a.removeEventListener("dragleave",f.xc);a.removeEventListener("dragover",f.yc);a.removeEventListener("drop",f.zc)},F:function(){f.dc&&f.dc.requestPointerLock&&f.dc.requestPointerLock()},Sa:function(a,b,c){var d=document.createElement("canvas");d.width=a;d.height=b;var e=d.getContext("2d"),h=
e.createImageData(a,b);h.data.set(E.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},u:function(){document.getElementById("_sokol_app_input_element").blur()},Ua:function(a){a=F(a);var b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left=
"-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},$a:function(){for(var a=(new URLSearchParams(window.location.search)).entries(),b=a.next();!b.done;b=a.next())ma("_sargs_add_kvp",["string","string"],[b.value[0],b.value[1]])},kb:function(){return f.cc?f.cc.bufferSize:0},mb:function(a,b,c){f.Yb=null;f.cc=null;"undefined"!==typeof AudioContext?f.Yb=new AudioContext({sampleRate:a,
latencyHint:"interactive"}):"undefined"!==typeof webkitAudioContext?f.Yb=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}):(f.Yb=null,console.log("sokol_audio.h: no WebAudio support"));return f.Yb?(console.log("sokol_audio.h: sample rate ",f.Yb.sampleRate),f.cc=f.Yb.createScriptProcessor(c,0,b),f.cc.onaudioprocess=function(d){var e=d.outputBuffer.length,h=Sb(e);if(h)for(var g=d.outputBuffer.numberOfChannels,m=0;m<g;m++)for(var n=d.outputBuffer.getChannelData(m),p=0;p<e;p++)n[p]=H[(h>>
2)+(g*p+m)]},f.cc.connect(f.Yb.destination),a=function(){f.Yb&&"suspended"===f.Yb.state&&f.Yb.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},lb:function(){return f.Yb?f.Yb.sampleRate:0},qa:function(){null!==f.Yb&&(f.cc&&f.cc.disconnect(),f.Yb.close(),f.Yb=null,f.cc=null)},E:function(a,b,c,d,e,h){b=F(b);var g=new XMLHttpRequest;g.open("GET",b);g.responseType="arraybuffer";var m=0<d;
m&&g.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));g.onreadystatechange=function(){if(this.readyState==this.DONE)if(206==this.status||200==this.status&&!m){var n=new Uint8Array(g.response),p=n.length;p<=h?(E.set(n,e),Tb(a,d,p)):Ub(a)}else Vb(a,this.status)};g.send()},pa:function(a,b){b=F(b);var c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(this.readyState==this.DONE)if(200==this.status){var d=this.getResponseHeader("Content-Length");Wb(a,d)}else Vb(a,this.status)};c.send()},
oa:function(){return navigator.userAgent.includes("Macintosh")?1:0},n:function(){return performance.now()}};
(function(){function a(e){f.asm=e.exports;ja=f.asm.Db;ya();za=f.asm.Xb;Ba.unshift(f.asm.Eb);J--;f.monitorRunDependencies&&f.monitorRunDependencies(J);0==J&&(null!==Ga&&(clearInterval(Ga),Ga=null),K&&(e=K,K=null,e()))}function b(e){a(e.instance)}function c(e){return Ka().then(function(h){return WebAssembly.instantiate(h,d)}).then(function(h){return h}).then(e,function(h){A("failed to asynchronously prepare wasm: "+h);z(h)})}var d={a:Xb};J++;f.monitorRunDependencies&&f.monitorRunDependencies(J);if(f.instantiateWasm)try{return f.instantiateWasm(d,
a)}catch(e){return A("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return B||"function"!==typeof WebAssembly.instantiateStreaming||Ha()||L.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(L,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(h){A("wasm streaming compile failed: "+h);A("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.Eb).apply(null,arguments)};var Qb=f.__sapp_emsc_notify_keyboard_hidden=function(){return(Qb=f.__sapp_emsc_notify_keyboard_hidden=f.asm.Fb).apply(null,arguments)};f.__sapp_emsc_onpaste=function(){return(f.__sapp_emsc_onpaste=f.asm.Gb).apply(null,arguments)};
var Nb=f.__sapp_html5_get_ask_leave_site=function(){return(Nb=f.__sapp_html5_get_ask_leave_site=f.asm.Hb).apply(null,arguments)},Ob=f.__sapp_emsc_begin_drop=function(){return(Ob=f.__sapp_emsc_begin_drop=f.asm.Ib).apply(null,arguments)};f.__sapp_emsc_drop=function(){return(f.__sapp_emsc_drop=f.asm.Jb).apply(null,arguments)};
var Pb=f.__sapp_emsc_end_drop=function(){return(Pb=f.__sapp_emsc_end_drop=f.asm.Kb).apply(null,arguments)},Rb=f.__sapp_emsc_invoke_fetch_cb=function(){return(Rb=f.__sapp_emsc_invoke_fetch_cb=f.asm.Lb).apply(null,arguments)};f._main=function(){return(f._main=f.asm.Mb).apply(null,arguments)};var Sb=f.__saudio_emsc_pull=function(){return(Sb=f.__saudio_emsc_pull=f.asm.Nb).apply(null,arguments)};f.__sargs_add_kvp=function(){return(f.__sargs_add_kvp=f.asm.Ob).apply(null,arguments)};
var Wb=f.__sfetch_emsc_head_response=function(){return(Wb=f.__sfetch_emsc_head_response=f.asm.Pb).apply(null,arguments)},Tb=f.__sfetch_emsc_get_response=function(){return(Tb=f.__sfetch_emsc_get_response=f.asm.Qb).apply(null,arguments)},Vb=f.__sfetch_emsc_failed_http_status=function(){return(Vb=f.__sfetch_emsc_failed_http_status=f.asm.Rb).apply(null,arguments)},Ub=f.__sfetch_emsc_failed_buffer_too_small=function(){return(Ub=f.__sfetch_emsc_failed_buffer_too_small=f.asm.Sb).apply(null,arguments)},Q=
f._malloc=function(){return(Q=f._malloc=f.asm.Tb).apply(null,arguments)},oa=f.stackSave=function(){return(oa=f.stackSave=f.asm.Ub).apply(null,arguments)},pa=f.stackRestore=function(){return(pa=f.stackRestore=f.asm.Vb).apply(null,arguments)},C=f.stackAlloc=function(){return(C=f.stackAlloc=f.asm.Wb).apply(null,arguments)},Yb;function fa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}K=function Zb(){Yb||$b();Yb||(K=Zb)};
function $b(a){function b(){if(!Yb&&(Yb=!0,f.calledRun=!0,!ka)){La(Ba);La(Ca);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(ac){var c=a,d=f._main;c=c||[];var e=c.length+1,h=C(4*(e+1));G[h>>2]=ta(ba);for(var g=1;g<e;g++)G[(h>>2)+g]=ta(c[g-1]);G[(h>>2)+e]=0;try{var m=d(e,h);if(!(noExitRuntime||0<ha)){if(f.onExit)f.onExit(m);ka=!0}q(m,new fa(m))}catch(n){n instanceof fa||"unwind"==n||q(1,n)}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)c=f.postRun.shift(),
Ea.unshift(c);La(Ea)}}a=a||aa;if(!(0<J)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Fa();La(Aa);0<J||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}f.run=$b;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var ac=!0;f.noInitialRun&&(ac=!1);$b();
